"""Contract type extraction schemas for ContractIQ multi-pass extraction."""

# Fields common across all contract types
COMMON_LEGAL_FIELDS = [
    "execution_date", "effective_date", "conditions_precedent_deadline",
    "financial_close_date", "commercial_operation_date",
    "longstop_date", "contract_term_years", "expiry_date",
    "extension_option_years", "extension_notice_period_days",
    "termination_for_convenience", "termination_notice_days",
    "termination_payment_formula", "material_breach_cure_period_days",
    "cross_default_provision", "insolvency_trigger",
    "change_of_control_trigger", "termination_fee_amount",
    "governing_law", "dispute_resolution_mechanism",
    "arbitration_rules", "arbitration_seat",
    "assignment_restriction", "lender_consent_required", "step_in_rights",
    "insurance_types_required", "minimum_coverage_amount",
    "business_interruption_coverage",
    "performance_guarantee_amount", "liquidated_damages_rate",
    "liquidated_damages_cap", "total_liability_cap",
    "consequential_damages_excluded", "indemnification_scope",
    "force_majeure_definition", "force_majeure_notification_period",
    "force_majeure_termination_threshold_days",
    "tax_gross_up_provision", "withholding_tax_treatment",
    "change_of_law_risk_allocation", "regulatory_approval_required",
    "confidentiality_term_years",
]

COMMON_RISK_FIELDS = [
    "subsidy_dependency", "renewable_certificate_type",
    "credit_rating_requirement", "sovereign_risk_country",
    "political_risk_insurance", "environmental_compliance_requirement",
]

CONTRACT_SCHEMAS: dict[str, dict[str, dict]] = {
    "ppa": {
        "pass_1_commercial": {
            "prompt_focus": "Commercial, pricing, and settlement terms for this Power Purchase Agreement",
            "section": "commercial_terms",
            "fields": [
                "contract_price_per_mwh", "price_currency", "price_type",
                "price_escalation_rate_pct", "price_escalation_mechanism",
                "price_escalation_start_year", "price_escalation_index",
                "price_floor_per_mwh", "price_cap_per_mwh",
                "baseload_price_per_mwh", "peak_price_per_mwh", "off_peak_price_per_mwh",
                "shape_premium_pct", "balancing_price_mechanism",
                "negative_price_mechanism", "negative_price_threshold",
                "annual_contract_quantity_mwh", "minimum_take_or_pay_pct",
                "maximum_delivery_mwh", "deemed_generation_provision",
                "curtailment_allocation_method", "curtailment_compensation_rate",
                "curtailment_cap_hours", "excess_energy_rate_pct",
                "shortfall_penalty_rate", "volume_flex_percentage",
                "nomination_deadline_hours", "renomination_rights",
                "settlement_period", "settlement_mechanism",
                "invoice_timing_days", "payment_terms_days",
                "late_payment_interest_rate_pct", "billing_currency",
                "fx_hedging_provision", "netting_provision",
                "credit_support_type", "credit_support_amount",
                "letter_of_credit_amount", "parent_guarantee_amount",
                "collateral_requirements", "margin_call_mechanism",
                "total_contract_value_estimate",
            ],
        },
        "pass_2_technical": {
            "prompt_focus": "Technical specifications, asset details, grid connection, and performance metrics",
            "section": "technical",
            "fields": [
                "project_name", "asset_name", "asset_type",
                "technology_type", "panel_manufacturer", "inverter_manufacturer",
                "tracker_type", "module_type",
                "nameplate_capacity_mwp", "ac_capacity_mw",
                "inverter_capacity_mw", "battery_storage_mwh",
                "number_of_units", "unit_capacity_mw",
                "capacity_factor_pct", "availability_guarantee_pct",
                "performance_ratio_pct", "degradation_rate_annual_pct",
                "minimum_annual_generation_mwh", "p50_generation_mwh",
                "p90_generation_mwh", "expected_useful_life_years",
                "grid_connection_point", "voltage_level_kv",
                "metering_point_id", "metering_arrangement",
                "interconnection_agreement_ref", "grid_code_compliance",
                "country", "region_state", "site_address",
                "coordinates_latitude", "coordinates_longitude", "time_zone",
                "irradiation_kwh_m2_year", "wind_speed_avg_m_s",
                "environmental_impact_assessment", "land_lease_term_years",
            ],
        },
        "pass_3_legal": {
            "prompt_focus": "Legal clauses, dates, termination, insurance, guarantees, and dispute resolution",
            "section": "legal",
            "fields": COMMON_LEGAL_FIELDS,
        },
        "pass_4_risk": {
            "prompt_focus": "Risk factors, regulatory, environmental, and special provisions",
            "section": "risk_factors",
            "fields": COMMON_RISK_FIELDS + [
                "curtailment_risk_level", "grid_congestion_risk",
                "resource_variability_risk", "technology_obsolescence_risk",
                "offtaker_credit_risk", "construction_delay_risk",
                "permitting_risk", "land_access_risk",
            ],
        },
    },
    "gas": {
        "pass_1_commercial": {
            "prompt_focus": "Commercial terms, pricing formula, volume commitments for Gas Supply Agreement",
            "section": "commercial_terms",
            "fields": [
                "contract_price_per_mmbtu", "price_currency", "price_formula",
                "index_reference", "index_adjustment_formula",
                "hub_reference_price", "transport_adder_per_mmbtu",
                "quality_premium_discount", "seasonal_pricing_mechanism",
                "price_review_mechanism", "price_review_frequency",
                "price_floor_per_mmbtu", "price_cap_per_mmbtu",
                "annual_contract_quantity_bcm", "annual_contract_quantity_mmbtu",
                "daily_contract_quantity_mmbtu", "maximum_daily_quantity_mmbtu",
                "minimum_daily_quantity_mmbtu", "swing_factor",
                "take_or_pay_percentage", "take_or_pay_base",
                "make_up_provision", "make_up_period_years",
                "carry_forward_provision", "carry_forward_period_years",
                "nomination_deadline_hours", "renomination_rights",
                "interruptible_quantity_pct", "interruptible_discount_pct",
                "settlement_period", "payment_terms_days",
                "late_payment_interest_rate_pct", "billing_currency",
                "credit_support_type", "credit_support_amount",
                "parent_guarantee_amount", "margin_call_mechanism",
                "total_contract_value_estimate",
            ],
        },
        "pass_2_technical": {
            "prompt_focus": "Technical specifications, gas quality, delivery points, storage, and pipeline details",
            "section": "technical",
            "fields": [
                "delivery_point", "redelivery_point",
                "pipeline_system", "pipeline_operator",
                "gas_quality_standard", "gross_calorific_value_min_mj",
                "gross_calorific_value_max_mj", "wobbe_index_min",
                "wobbe_index_max", "methane_content_min_pct",
                "h2s_limit_ppm", "co2_limit_pct",
                "nitrogen_limit_pct", "oxygen_limit_pct",
                "moisture_content_limit", "hydrocarbon_dewpoint",
                "pressure_bar_min", "pressure_bar_max",
                "temperature_range_celsius", "flow_rate_measurement_method",
                "metering_station", "metering_responsibility",
                "metering_accuracy_standard",
                "storage_facility_name", "storage_capacity_mcm",
                "injection_rate_mcm_day", "withdrawal_rate_mcm_day",
                "cushion_gas_obligation",
                "lng_terminal", "regasification_capacity",
                "shipping_terms", "vessel_requirements",
                "country_origin", "country_destination",
            ],
        },
        "pass_3_legal": {
            "prompt_focus": "Legal clauses, dates, termination, insurance, guarantees",
            "section": "legal",
            "fields": COMMON_LEGAL_FIELDS,
        },
        "pass_4_risk": {
            "prompt_focus": "Risk factors, regulatory, supply chain, geopolitical risks",
            "section": "risk_factors",
            "fields": COMMON_RISK_FIELDS + [
                "supply_disruption_risk", "geopolitical_risk_countries",
                "sanctions_compliance", "shipping_route_risk",
                "storage_injection_risk", "seasonal_demand_risk",
                "pipeline_capacity_constraint_risk",
                "gas_quality_rejection_risk", "force_majeure_gas_specific",
            ],
        },
    },
    "tolling": {
        "pass_1_commercial": {
            "prompt_focus": "Commercial terms for Tolling/Processing Agreement",
            "section": "commercial_terms",
            "fields": [
                "capacity_payment_per_mw_month", "energy_payment_per_mwh",
                "start_up_payment", "hot_standby_rate",
                "heat_rate_btu_kwh", "guaranteed_heat_rate",
                "fuel_type", "fuel_specification",
                "dispatch_rights_holder", "minimum_dispatch_notice_hours",
                "minimum_run_time_hours", "minimum_down_time_hours",
                "ramp_rate_mw_min", "maximum_starts_per_year",
                "availability_guarantee_pct", "capacity_factor_guarantee",
                "forced_outage_rate_cap_pct", "planned_maintenance_days",
                "bonus_payment_availability", "penalty_unavailability",
                "settlement_period", "payment_terms_days",
                "total_contract_value_estimate",
            ],
        },
        "pass_2_technical": {
            "prompt_focus": "Technical specifications for tolling facility",
            "section": "technical",
            "fields": [
                "plant_name", "plant_type", "generation_technology",
                "nameplate_capacity_mw", "net_capacity_mw",
                "number_of_units", "unit_capacity_mw",
                "emissions_rate_tco2_mwh", "water_consumption_rate",
                "noise_limit_db", "grid_connection_point",
                "fuel_delivery_point", "fuel_storage_capacity",
                "country", "region_state", "site_address",
            ],
        },
        "pass_3_legal": {
            "prompt_focus": "Legal clauses, dates, termination, insurance, guarantees",
            "section": "legal",
            "fields": COMMON_LEGAL_FIELDS,
        },
        "pass_4_risk": {
            "prompt_focus": "Risk factors for tolling arrangement",
            "section": "risk_factors",
            "fields": COMMON_RISK_FIELDS + [
                "fuel_supply_risk", "emissions_compliance_risk",
                "equipment_failure_risk", "grid_curtailment_risk",
            ],
        },
    },
    "vppa": {
        "pass_1_commercial": {
            "prompt_focus": "Commercial terms for Virtual Power Purchase Agreement (financial settlement)",
            "section": "commercial_terms",
            "fields": [
                "fixed_price_per_mwh", "price_currency",
                "settlement_hub", "settlement_node",
                "settlement_reference_price_index",
                "contract_for_differences_mechanism",
                "volume_mwh_annual", "shape_risk_allocation",
                "basis_risk_allocation", "proxy_generation_methodology",
                "proxy_revenue_calculation", "settlement_frequency",
                "payment_netting", "collateral_requirements",
                "rec_allocation_pct", "rec_type",
                "rec_delivery_mechanism", "rec_price_if_separate",
                "additionality_certification", "green_attribute_ownership",
                "total_contract_value_estimate",
            ],
        },
        "pass_2_technical": {
            "prompt_focus": "Technical specifications of the virtual PPA project",
            "section": "technical",
            "fields": [
                "project_name", "technology_type", "nameplate_capacity_mw",
                "expected_annual_generation_mwh", "capacity_factor_pct",
                "p50_generation", "p90_generation",
                "project_location", "grid_region",
                "iso_rto", "balancing_authority",
            ],
        },
        "pass_3_legal": {
            "prompt_focus": "Legal clauses for VPPA",
            "section": "legal",
            "fields": COMMON_LEGAL_FIELDS,
        },
        "pass_4_risk": {
            "prompt_focus": "Risk factors for virtual PPA",
            "section": "risk_factors",
            "fields": COMMON_RISK_FIELDS + [
                "basis_risk_level", "shape_risk_level",
                "proxy_generation_risk", "counterparty_credit_risk",
                "accounting_treatment_risk", "regulatory_change_risk",
            ],
        },
    },
    "metals": {
        "pass_1_commercial": {
            "prompt_focus": "Commercial terms of a precious-metals contract",
            "section": "commercial",
            "fields": [
                "buyer_name", "seller_name", "execution_date",
                "effective_date", "expiry_date",
                "material", "material_form", "fineness_min", "fineness_target",
                "bar_weight_oz", "bar_weight_tolerance_pct",
                "good_delivery_standard", "accepted_refiners",
                "loco", "delivery_window_days",
                "pricing_reference", "pricing_formula", "settlement_currency",
                "payment_terms_days", "provisional_payment_pct",
                "treatment_charge_per_tonne_usd", "refining_charge_per_oz_usd",
                "payable_percent_au", "payable_percent_ag",
                "payable_percent_pt", "payable_percent_pd",
                "moisture_adjustment_threshold_pct",
                "total_contract_value_estimate",
            ],
        },
        "pass_2_quality": {
            "prompt_focus": "Assay, sampling and quality clauses",
            "section": "quality",
            "fields": [
                "assay_method", "assay_tolerance_pct",
                "umpire_clause_present", "split_sample_protocol",
                "impurity_penalties", "weight_variance_protocol",
                "rejection_criteria", "sampling_frequency",
            ],
        },
        "pass_3_legal": {
            "prompt_focus": "Legal clauses for the precious-metals contract",
            "section": "legal",
            "fields": COMMON_LEGAL_FIELDS + [
                "vaulting_type", "insurance_required",
                "insurance_min_coverage_pct", "chain_of_integrity_required",
                "repatriation_right", "good_delivery_termination_clause",
            ],
        },
        "pass_4_compliance": {
            "prompt_focus": "Compliance + sanctions clauses",
            "section": "compliance",
            "fields": [
                "references_lbma_rgg", "references_lppm",
                "references_oecd_ddg", "references_rjc",
                "references_dodd_frank_1502", "references_eu_2017_821",
                "references_iso_9001", "references_iso_14001",
                "references_swiss_pmca", "references_reach",
                "references_hmrc_vat_701_14",
                "russian_origin_excluded", "ofac_clause_present",
            ],
        },
        "pass_5_risk": {
            "prompt_focus": "Risk factors specific to precious metals",
            "section": "risk_factors",
            "fields": COMMON_RISK_FIELDS + [
                "assay_dispute_risk", "weight_variance_risk",
                "loco_premium_risk", "lease_rate_risk",
                "refiner_list_dependency", "sanctioned_origin_risk",
                "brand_acceptability_risk",
            ],
        },
    },
}


def get_schema_for_type(contract_type: str) -> dict[str, dict]:
    """Get extraction schema for a contract type, with PPA as default fallback."""
    return CONTRACT_SCHEMAS.get(contract_type, CONTRACT_SCHEMAS["ppa"])


def get_total_fields(contract_type: str) -> int:
    """Count total fields across all passes for a contract type."""
    schema = get_schema_for_type(contract_type)
    return sum(len(p["fields"]) for p in schema.values())
