apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-runtime.fullname" . }}-secret
  labels:
    {{- include "edge-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  platform_token: {{ .Values.platform_token | quote }}
  anthropic_api_key: {{ .Values.anthropic_api_key | quote }}
  signing_pubkey: |-
    {{- .Values.signing_pubkey | nindent 4 }}
