/**
 * Deep end-to-end test of the Functional Analysis DAG modal redesign.
 *
 * Flow:
 *   1. Login to ContractIQ
 *   2. Upload a fresh contract (LNG tolling — exercises OP + CP categories)
 *   3. Wait for extraction (status=analyzed)
 *   4. Trigger functional-analysis agent
 *   5. Navigate to the Functional Analysis tab
 *   6. Verify clause DAG renders with 11+ rule categories
 *   7. Click a Payment node (the main convergence point)
 *   8. Verify 2-panel modal:
 *        LEFT  — attributes + upstream/downstream chips
 *        RIGHT — event sub-DAG (events generated by this clause)
 *   9. Click an event in the sub-DAG → verify event details panel appears
 *  10. Close modal
 *
 * Run:
 *   BASE_URL=http://localhost:3001 API_URL=http://localhost:8001 \
 *     npx playwright test e2e/test_fa_dag_modal.spec.ts --reporter=list
 */
import { test, expect, type Page } from '@playwright/test';
import * as path from 'path';

const BASE_URL = process.env.BASE_URL || 'http://localhost:3001';
const API_URL = process.env.API_URL || 'http://localhost:8001';
const EMAIL = 'test@contractiq.com';
const PASSWORD = 'TestPass123!';

// Reuse the smallest contract that exercises multiple clause types
const TEST_CONTRACT = path.resolve(
  __dirname, '..', 'test-contracts', 'lng_tolling_agreement_qatar.txt'
);

test.describe.serial('ContractIQ FA DAG Modal — end-to-end on Azure', () => {
  let token: string;
  let contractId: string;

  test('00. Login', async ({ request }) => {
    const r = await request.post(`${API_URL}/api/contractiq/auth/login`, {
      data: { email: EMAIL, password: PASSWORD },
    });
    expect(r.status()).toBe(200);
    token = (await r.json()).data.access_token;
  });

  test('01. Upload a new contract', async ({ request }) => {
    test.setTimeout(60_000);
    const fs = await import('fs');
    const buf = fs.readFileSync(TEST_CONTRACT);
    const r = await request.post(`${API_URL}/api/contractiq/contracts/upload`, {
      headers: { Authorization: `Bearer ${token}` },
      multipart: {
        file: { name: 'lng_tolling.txt', mimeType: 'text/plain', buffer: buf },
        title: `LNG Tolling — FA DAG E2E ${Date.now()}`,
        contract_type: 'tolling',
        counterparty_a: 'Qatargas 4 LNG',
        counterparty_b: 'Offtaker Corp',
      },
      timeout: 60_000,
    });
    expect(r.status()).toBeLessThan(300);
    const b = await r.json();
    contractId = b.data?.id;
    expect(contractId).toBeTruthy();
  });

  test('02. Extract (produces clauses, deal_clusters, and classification attrs)', async ({ request }) => {
    test.setTimeout(420_000);
    const r = await request.post(`${API_URL}/api/contractiq/contracts/${contractId}/extract`, {
      headers: { Authorization: `Bearer ${token}` },
      timeout: 360_000,
    });
    expect(r.status()).toBeLessThan(500);
    const text = await r.text();
    // Must succeed (look for 'done' SSE event + analyzed status)
    expect(text).toMatch(/event":\s*"done"|"status":\s*"analyzed"/);
  });

  test('03. Run Functional Analysis — produces 11+ rule categories + DAG', async ({ request }) => {
    test.setTimeout(420_000);
    const r = await request.post(
      `${API_URL}/api/contractiq/contracts/${contractId}/functional-analysis`,
      { headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, data: {}, timeout: 360_000 }
    );
    expect(r.status()).toBeLessThan(500);
    const b = await r.json();
    // Response shape: {data: {contract_id, analysis: {<categories>}}}
    const fa = (b.data && b.data.analysis) ? b.data.analysis : (b.analysis || b.data || b);
    const categoriesWithRules = [
      'electricity_delivery_rules',
      'gas_delivery_rules',
      'price_market_data_rules',
      'volumetric_timeseries_rules',
      'payment_rules',
      'capacity_rules',
      'optionality_rules',
      'termination_rules',
    ].filter(k => Array.isArray(fa[k]) && fa[k].length > 0);
    console.log('FA categories with rules:', categoriesWithRules);
    expect(categoriesWithRules.length).toBeGreaterThanOrEqual(3);
    // DAG linked_rules semantics: PM should have ED or GD or PR upstream
    const allPm = fa.payment_rules || [];
    if (allPm.length) {
      const pmFirst = allPm[0];
      const links = pmFirst.linked_rules || [];
      console.log('PM-1 linked_rules:', links);
      const hasUpstream = links.some((l: string) => /^(ED|GD|PR|VT|OP|CP)/.test(l));
      expect(hasUpstream).toBe(true);
    }
  });

  test('04. UI: Contract detail page → FA tab → clause DAG renders', async ({ page }) => {
    // UI login
    await page.goto(BASE_URL);
    await page.waitForLoadState('networkidle');
    const signIn = page.getByRole('button', { name: /sign in/i }).first();
    if (await signIn.isVisible({ timeout: 3000 }).catch(() => false)) await signIn.click();
    await page.locator('input[type="email"]').first().fill(EMAIL);
    await page.locator('input[type="password"]').first().fill(PASSWORD);
    await page.getByRole('button', { name: /sign in|log in/i }).last().click();
    await page.waitForURL(/\/(dashboard|insights|contracts)/, { timeout: 15_000 });

    // Go straight to the contract detail page
    await page.goto(`${BASE_URL}/contracts/${contractId}`);
    await page.waitForLoadState('networkidle', { timeout: 20_000 });

    // Switch to "Functional Analysis" tab
    const faTab = page.getByRole('button', { name: /Functional Analysis/i });
    await faTab.click();
    await page.waitForTimeout(1500);

    // The clause DAG must be visible
    const dag = page.locator('[data-testid=fa-clause-dag]');
    await expect(dag).toBeVisible({ timeout: 10_000 });
    // At least a few nodes should be present
    const nodeCount = await page.locator('[data-testid^=fa-node-]').count();
    console.log('Clause DAG node count:', nodeCount);
    expect(nodeCount).toBeGreaterThanOrEqual(3);
  });

  test('05. Click a node → 2-panel modal opens with details + event sub-DAG', async ({ page }) => {
    // Reuse login flow
    await page.goto(BASE_URL);
    await page.waitForLoadState('networkidle');
    const signIn = page.getByRole('button', { name: /sign in/i }).first();
    if (await signIn.isVisible({ timeout: 3000 }).catch(() => false)) await signIn.click();
    await page.locator('input[type="email"]').first().fill(EMAIL);
    await page.locator('input[type="password"]').first().fill(PASSWORD);
    await page.getByRole('button', { name: /sign in|log in/i }).last().click();
    await page.waitForURL(/\/(dashboard|insights|contracts)/, { timeout: 15_000 });

    await page.goto(`${BASE_URL}/contracts/${contractId}`);
    await page.waitForLoadState('networkidle', { timeout: 20_000 });
    await page.getByRole('button', { name: /Functional Analysis/i }).click();
    await page.waitForTimeout(1500);

    // Click the first node — any type
    const firstNode = page.locator('[data-testid^=fa-node-]').first();
    await firstNode.click();

    // Modal appears
    const modal = page.locator('[data-testid=fa-clause-dag-detail]');
    await expect(modal).toBeVisible({ timeout: 5000 });

    // LEFT panel — Attributes label
    await expect(modal).toContainText(/Attributes/i);

    // RIGHT panel — either event sub-DAG OR at least neighbours chips
    // (some nodes may have no events; sub-DAG renders only when events exist)
    const hasEventsHeader = await modal.locator('text=/Events generated by this clause/i').isVisible({ timeout: 2000 }).catch(() => false);
    const hasFeedsChips = await modal.locator('text=/Feeds in|Feeds out to/i').first().isVisible({ timeout: 2000 }).catch(() => false);
    console.log('Modal has events header:', hasEventsHeader, 'neighbours chips:', hasFeedsChips);
    expect(hasEventsHeader || hasFeedsChips).toBe(true);
  });

  test('06. Close modal via Escape', async ({ page }) => {
    await page.goto(BASE_URL);
    await page.waitForLoadState('networkidle');
    const signIn = page.getByRole('button', { name: /sign in/i }).first();
    if (await signIn.isVisible({ timeout: 3000 }).catch(() => false)) await signIn.click();
    await page.locator('input[type="email"]').first().fill(EMAIL);
    await page.locator('input[type="password"]').first().fill(PASSWORD);
    await page.getByRole('button', { name: /sign in|log in/i }).last().click();
    await page.waitForURL(/\/(dashboard|insights|contracts)/, { timeout: 15_000 });

    await page.goto(`${BASE_URL}/contracts/${contractId}`);
    await page.waitForLoadState('networkidle');
    await page.getByRole('button', { name: /Functional Analysis/i }).click();
    await page.waitForTimeout(1000);

    await page.locator('[data-testid^=fa-node-]').first().click();
    await expect(page.locator('[data-testid=fa-clause-dag-detail]')).toBeVisible();
    await page.keyboard.press('Escape');
    await expect(page.locator('[data-testid=fa-clause-dag-detail]')).not.toBeVisible();
  });
});
