"""Saved Tool — Admin-approved custom tools persisted for reuse."""

import uuid
from typing import Optional

from sqlalchemy import (
    Boolean,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from models.base import Base, TenantMixin, TimestampMixin, UUIDMixin


class SavedTool(Base, UUIDMixin, TenantMixin, TimestampMixin):
    """A custom tool generated by AI and saved for reuse."""

    __tablename__ = "saved_tools"

    name: Mapped[str] = mapped_column(String(100), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    code: Mapped[str] = mapped_column(Text, nullable=False)  # Python source
    input_schema: Mapped[dict] = mapped_column(JSONB, default={})

    created_by: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    approved_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=True
    )

    status: Mapped[str] = mapped_column(
        String(20), default="pending"  # pending | approved | rejected
    )
    is_public: Mapped[bool] = mapped_column(Boolean, default=False)
    usage_count: Mapped[int] = mapped_column(Integer, default=0)

    review_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    review_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Elevated permissions (require admin approval)
    permissions: Mapped[dict] = mapped_column(
        JSONB,
        default={
            "network": False,
            "filesystem_read": False,
            "filesystem_write": False,
            "third_party": [],
            "env_vars": [],
        },
    )

    __table_args__ = (
        UniqueConstraint("tenant_id", "name", name="uq_saved_tool_tenant_name"),
        Index("ix_saved_tool_status", "tenant_id", "status"),
    )
