apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescaledb.fullname" . }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: postgres
      port: {{ .Values.service.port | default 5432 }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "timescaledb.selectorLabels" . | nindent 4 }}
