"""initial"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05ce612575be"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mcp_registry_cache",
        sa.Column("registry_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("server_url", sa.String(length=1000), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.Column("categories", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("tools_count", sa.Integer(), nullable=False),
        sa.Column("popularity_score", sa.Integer(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_mcp_registry_cache_registry_id"),
        "mcp_registry_cache",
        ["registry_id"],
        unique=True,
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column(
            "plan",
            sa.Enum("FREE", "PRO", "BUSINESS", "ENTERPRISE", name="tenant_plan"),
            nullable=False,
        ),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "CREATOR", "USER", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "agents",
        sa.Column("creator_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column(
            "model_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "agent_type",
            sa.Enum("CUSTOM", "OOB", "VERTICAL", name="agent_type"),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column(
            "marketplace_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="agent_status"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agents_creator_id"), "agents", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=False)
    op.create_index("ix_agents_status", "agents", ["tenant_id", "status"], unique=False)
    op.create_index(
        "ix_agents_tenant_created", "agents", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_agents_tenant_id"), "agents", ["tenant_id"], unique=False)
    op.create_table(
        "user_mcp_connections",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("server_name", sa.String(length=255), nullable=False),
        sa.Column("server_url", sa.String(length=1000), nullable=False),
        sa.Column("transport_type", sa.String(length=50), nullable=False),
        sa.Column("auth_type", sa.String(length=50), nullable=False),
        sa.Column(
            "auth_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "discovered_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("health_status", sa.String(length=50), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_mcp_conn_tenant_user",
        "user_mcp_connections",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_mcp_connections_tenant_id"),
        "user_mcp_connections",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_mcp_connections_user_id"),
        "user_mcp_connections",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "agent_mcp_tools",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("mcp_connection_id", sa.UUID(), nullable=False),
        sa.Column("tool_name", sa.String(length=255), nullable=False),
        sa.Column(
            "tool_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column("max_calls_per_execution", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mcp_connection_id"],
            ["user_mcp_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_mcp_tools_agent",
        "agent_mcp_tools",
        ["agent_id", "mcp_connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_mcp_tools_agent_id"),
        "agent_mcp_tools",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_mcp_tools_mcp_connection_id"),
        "agent_mcp_tools",
        ["mcp_connection_id"],
        unique=False,
    )
    op.create_table(
        "executions",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("input_message", sa.Text(), nullable=False),
        sa.Column("output_message", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="execution_status"
            ),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_executions_agent_id"), "executions", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_executions_agent_status", "executions", ["agent_id", "status"], unique=False
    )
    op.create_index(
        "ix_executions_tenant_created",
        "executions",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_executions_tenant_id"), "executions", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_executions_user_agent", "executions", ["user_id", "agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_executions_user_id"), "executions", ["user_id"], unique=False
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.String(length=100), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("chunk_overlap", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PROCESSING", "READY", "FAILED", name="kb_status"),
            nullable=False,
        ),
        sa.Column("doc_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_kb_tenant_created",
        "knowledge_bases",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_bases_agent_id"),
        "knowledge_bases",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_bases_tenant_id"),
        "knowledge_bases",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reviews_agent", "reviews", ["agent_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_reviews_agent_id"), "reviews", ["agent_id"], unique=False)
    op.create_index(
        "ix_reviews_user_agent", "reviews", ["user_id", "agent_id"], unique=False
    )
    op.create_index(op.f("ix_reviews_user_id"), "reviews", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("plan_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscriptions_agent_id"), "subscriptions", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_subscriptions_user_agent",
        "subscriptions",
        ["user_id", "agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "usage_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column(
            "record_type",
            sa.Enum("EXECUTION", "TOKEN", "STORAGE", name="record_type"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("cost", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_records_agent_id"), "usage_records", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_records_tenant_id"), "usage_records", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_records_user_id"), "usage_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_usage_tenant_created",
        "usage_records",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_user_type", "usage_records", ["user_id", "record_type"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("kb_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=500), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PROCESSING", "READY", "FAILED", name="document_status"),
            nullable=False,
        ),
        sa.Column("storage_url", sa.String(length=1000), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["kb_id"],
            ["knowledge_bases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_kb_id"), "documents", ["kb_id"], unique=False)
    op.create_index(
        "ix_documents_kb_status", "documents", ["kb_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_documents_kb_status", table_name="documents")
    op.drop_index(op.f("ix_documents_kb_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_usage_user_type", table_name="usage_records")
    op.drop_index("ix_usage_tenant_created", table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_user_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_tenant_id"), table_name="usage_records")
    op.drop_index(op.f("ix_usage_records_agent_id"), table_name="usage_records")
    op.drop_table("usage_records")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_user_agent", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_agent_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_reviews_user_id"), table_name="reviews")
    op.drop_index("ix_reviews_user_agent", table_name="reviews")
    op.drop_index(op.f("ix_reviews_agent_id"), table_name="reviews")
    op.drop_index("ix_reviews_agent", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_knowledge_bases_tenant_id"), table_name="knowledge_bases")
    op.drop_index(op.f("ix_knowledge_bases_agent_id"), table_name="knowledge_bases")
    op.drop_index("ix_kb_tenant_created", table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_index(op.f("ix_executions_user_id"), table_name="executions")
    op.drop_index("ix_executions_user_agent", table_name="executions")
    op.drop_index(op.f("ix_executions_tenant_id"), table_name="executions")
    op.drop_index("ix_executions_tenant_created", table_name="executions")
    op.drop_index("ix_executions_agent_status", table_name="executions")
    op.drop_index(op.f("ix_executions_agent_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_index(
        op.f("ix_agent_mcp_tools_mcp_connection_id"), table_name="agent_mcp_tools"
    )
    op.drop_index(op.f("ix_agent_mcp_tools_agent_id"), table_name="agent_mcp_tools")
    op.drop_index("ix_agent_mcp_tools_agent", table_name="agent_mcp_tools")
    op.drop_table("agent_mcp_tools")
    op.drop_index(
        op.f("ix_user_mcp_connections_user_id"), table_name="user_mcp_connections"
    )
    op.drop_index(
        op.f("ix_user_mcp_connections_tenant_id"), table_name="user_mcp_connections"
    )
    op.drop_index("ix_mcp_conn_tenant_user", table_name="user_mcp_connections")
    op.drop_table("user_mcp_connections")
    op.drop_index(op.f("ix_agents_tenant_id"), table_name="agents")
    op.drop_index("ix_agents_tenant_created", table_name="agents")
    op.drop_index("ix_agents_status", table_name="agents")
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.drop_index(op.f("ix_agents_creator_id"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(
        op.f("ix_mcp_registry_cache_registry_id"), table_name="mcp_registry_cache"
    )
    op.drop_table("mcp_registry_cache")
    # ### end Alembic commands ###
