'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { PageExplainer } from '@/components/PageExplainer';
import {
  Sunrise, Sparkles, Loader2, AlertCircle, CheckCircle2, Clock,
  ChevronLeft, RefreshCw, TrendingDown, TrendingUp, Activity, Upload,
} from 'lucide-react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || '';
function getToken() { return typeof window !== 'undefined' ? localStorage.getItem('contractiq_token') : null; }

interface Briefing {
  id: string;
  for_date: string;
  status: string;
  headline: string | null;
  body_markdown: string | null;
  metrics: any;
  top_actions: any[] | null;
  cost_usd: number | null;
  duration_ms: number | null;
  error_message: string | null;
  created_at: string;
}

function RichText({ md }: { md: string }) {
  // Simple markdown: ##, **bold**, lists, paragraphs
  const lines = md.split('\n');
  return (
    <div className="space-y-2 text-sm text-slate-300 leading-relaxed">
      {lines.map((line, i) => {
        if (line.startsWith('## ')) return <h3 key={i} className="text-base font-bold text-white mt-4 mb-1">{line.slice(3)}</h3>;
        if (line.startsWith('### ')) return <h4 key={i} className="text-sm font-semibold text-white mt-3 mb-1">{line.slice(4)}</h4>;
        if (line.startsWith('- ')) return <div key={i} className="flex items-start gap-2 ml-2"><span className="text-emerald-400 mt-1.5 text-[6px]">●</span><span>{renderInline(line.slice(2))}</span></div>;
        if (line.trim() === '') return <div key={i} className="h-2" />;
        return <p key={i}>{renderInline(line)}</p>;
      })}
    </div>
  );
}

function renderInline(text: string) {
  const parts = text.split(/(\*\*.*?\*\*)/);
  return parts.map((p, i) => p.startsWith('**') && p.endsWith('**') ? <strong key={i} className="text-white">{p.slice(2, -2)}</strong> : <span key={i}>{p}</span>);
}

export default function BriefingPage() {
  const [briefing, setBriefing] = useState<Briefing | null>(null);
  const [history, setHistory] = useState<Briefing[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [contractCount, setContractCount] = useState<number | null>(null);

  const load = async () => {
    setLoading(true);
    const token = getToken();
    if (!token) return;
    const [todayRes, histRes, portfolioRes] = await Promise.all([
      fetch(`${API_URL}/api/contractiq/insights/briefing/today`, { headers: { Authorization: `Bearer ${token}` } }),
      fetch(`${API_URL}/api/contractiq/insights/briefing/history?limit=10`, { headers: { Authorization: `Bearer ${token}` } }),
      fetch(`${API_URL}/api/contractiq/analytics/portfolio`, { headers: { Authorization: `Bearer ${token}` } }),
    ]);
    const todayBody = await todayRes.json();
    const histBody = await histRes.json();
    const portfolioBody = await portfolioRes.json().catch(() => ({}));
    setBriefing(todayBody.data);
    setHistory(histBody.data || []);
    const tc = portfolioBody?.data?.total_contracts;
    setContractCount(typeof tc === 'number' ? tc : 0);
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  const hasPortfolio = (contractCount ?? 0) >= 1;

  const generate = async () => {
    if (!hasPortfolio) return;
    setGenerating(true);
    const token = getToken();
    try {
      const res = await fetch(`${API_URL}/api/contractiq/insights/briefing/generate`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      const body = await res.json();
      setBriefing(body.data);
      // Refresh history
      const histRes = await fetch(`${API_URL}/api/contractiq/insights/briefing/history?limit=10`, { headers: { Authorization: `Bearer ${token}` } });
      setHistory((await histRes.json()).data || []);
    } finally {
      setGenerating(false);
    }
  };

  const metrics = briefing?.metrics || {};

  return (
    <div className="min-h-screen bg-[#0B0F19] p-8">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div>
            <a href="/insights" className="inline-flex items-center gap-1 text-xs text-slate-500 hover:text-emerald-400 mb-2">
              <ChevronLeft className="w-3 h-3" /> Back to Insights Hub
            </a>
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-amber-500/20 to-orange-600/20 border border-amber-500/30 flex items-center justify-center">
                <Sunrise className="w-6 h-6 text-amber-400" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white">Daily Executive Briefing</h1>
                <p className="text-xs text-slate-400">Your portfolio in 1 page, generated by <code className="text-amber-300">contractiq-executive-briefing</code></p>
              </div>
            </div>
          </div>
          <button
            onClick={generate}
            disabled={generating || !hasPortfolio}
            title={!hasPortfolio ? 'Upload a contract first — briefings need a portfolio' : undefined}
            className="px-4 py-2 rounded-lg bg-gradient-to-r from-amber-500 to-orange-600 text-white text-sm font-semibold hover:shadow-lg hover:shadow-amber-500/25 transition-all flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {generating ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Sparkles className="w-4 h-4" /> Generate Today's Briefing</>}
          </button>
        </div>
        <PageExplainer routeKey="insights-briefing" />

        {loading ? (
          <div className="flex items-center justify-center h-64">
            <Loader2 className="w-8 h-8 animate-spin text-amber-400" />
          </div>
        ) : !hasPortfolio ? (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-12 text-center">
            <Upload className="w-12 h-12 text-amber-400/60 mx-auto mb-3" />
            <p className="text-sm text-white font-semibold mb-1">Upload a contract first — briefings need a portfolio</p>
            <p className="text-xs text-slate-400 mb-5">The briefing agent reads your contracts, alerts, and MtM exposure. With zero contracts there is nothing to brief on.</p>
            <a href="/upload" className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-gradient-to-r from-amber-500 to-orange-600 text-white text-sm font-semibold hover:shadow-lg hover:shadow-amber-500/25 transition-all">
              <Upload className="w-4 h-4" /> Upload Contract
            </a>
          </motion.div>
        ) : !briefing ? (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-xl border border-slate-800/50 bg-slate-900/30 p-12 text-center">
            <Sunrise className="w-12 h-12 text-amber-400/40 mx-auto mb-3" />
            <p className="text-sm text-slate-400 mb-2">No briefing yet today.</p>
            <p className="text-xs text-slate-500">Click "Generate Today's Briefing" to create one.</p>
          </motion.div>
        ) : briefing.status === 'failed' ? (
          <div className="rounded-xl border border-red-500/30 bg-red-500/5 p-6">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-red-400 mt-0.5" />
              <div>
                <h3 className="text-sm font-semibold text-red-300 mb-1">Briefing generation failed</h3>
                <p className="text-xs text-slate-400">{briefing.error_message || 'Unknown error'}</p>
              </div>
            </div>
          </div>
        ) : (
          <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-6">
            {/* Headline card */}
            <div className="rounded-xl border border-amber-500/30 bg-gradient-to-br from-amber-500/5 to-orange-500/5 p-6">
              <div className="flex items-start gap-3">
                <Sparkles className="w-5 h-5 text-amber-400 mt-1 shrink-0" />
                <div className="flex-1">
                  <p className="text-[10px] text-amber-300/60 uppercase tracking-wider mb-1">Headline</p>
                  <p className="text-xl font-bold text-white leading-snug">{briefing.headline}</p>
                </div>
              </div>
            </div>

            {/* Metrics row */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
              {[
                { label: 'Contracts', value: metrics.total_contracts, icon: Activity },
                { label: 'Total MW', value: metrics.total_capacity_mw, icon: TrendingUp },
                { label: 'Alerts (24h)', value: metrics.alerts_overnight, icon: AlertCircle },
                {
                  label: 'MtM Δ',
                  value: metrics.mtm_change_pct != null ? `${metrics.mtm_change_pct > 0 ? '+' : ''}${metrics.mtm_change_pct}%` : '—',
                  icon: metrics.mtm_change_pct < 0 ? TrendingDown : TrendingUp,
                  color: metrics.mtm_change_pct < 0 ? 'text-red-400' : 'text-emerald-400',
                },
              ].map((m, i) => (
                <div key={i} className="rounded-xl border border-slate-800/50 bg-slate-900/30 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <m.icon className={`w-4 h-4 ${m.color || 'text-slate-500'}`} />
                    <span className="text-[10px] text-slate-500 uppercase tracking-wider">{m.label}</span>
                  </div>
                  <p className={`text-2xl font-bold ${m.color || 'text-white'}`}>{m.value ?? '—'}</p>
                </div>
              ))}
            </div>

            {/* Top actions */}
            {briefing.top_actions && briefing.top_actions.length > 0 && (
              <div className="rounded-xl border border-slate-800/50 bg-slate-900/30 p-5">
                <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" /> Top Action Items
                </h3>
                <div className="space-y-2">
                  {briefing.top_actions.map((a: any, i: number) => (
                    <div key={i} className="flex items-start gap-3 p-3 rounded-lg bg-slate-800/30 border border-slate-700/30 hover:border-emerald-500/30 transition-colors">
                      <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase ${a.priority === 'high' ? 'bg-red-500/20 text-red-300' : a.priority === 'medium' ? 'bg-amber-500/20 text-amber-300' : 'bg-slate-500/20 text-slate-300'}`}>
                        {a.priority}
                      </span>
                      <div className="flex-1">
                        <p className="text-sm text-white font-medium">{a.title}</p>
                        {a.contract && <p className="text-xs text-slate-400 mt-0.5">{a.contract}</p>}
                      </div>
                      {a.due && <span className="text-xs text-slate-500 shrink-0">{a.due}</span>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Body markdown */}
            {briefing.body_markdown && (
              <div className="rounded-xl border border-slate-800/50 bg-slate-900/30 p-6">
                <h3 className="text-sm font-semibold text-white mb-3">Full Briefing</h3>
                <RichText md={briefing.body_markdown} />
              </div>
            )}

            {/* Meta */}
            <div className="flex items-center gap-4 text-xs text-slate-500">
              <span className="flex items-center gap-1"><Clock className="w-3 h-3" /> {briefing.duration_ms ? `${(briefing.duration_ms / 1000).toFixed(1)}s` : '—'}</span>
              {briefing.cost_usd != null && <span>${briefing.cost_usd.toFixed(4)} cost</span>}
              <span>Generated {new Date(briefing.created_at).toLocaleString()}</span>
            </div>
          </motion.div>
        )}

        {/* History */}
        {history.length > 1 && (
          <div className="mt-10">
            <h3 className="text-sm font-semibold text-slate-400 mb-3 flex items-center gap-2">
              <RefreshCw className="w-3.5 h-3.5" /> Recent Briefings
            </h3>
            <div className="space-y-2">
              {history.slice(0, 5).map((h) => (
                <div key={h.id} className="rounded-lg border border-slate-800/50 bg-slate-900/20 p-3 flex items-center gap-3">
                  <div className={`w-2 h-2 rounded-full ${h.status === 'completed' ? 'bg-emerald-400' : h.status === 'failed' ? 'bg-red-400' : 'bg-amber-400'}`} />
                  <p className="text-xs text-slate-300 flex-1 truncate">{h.headline || '(no headline)'}</p>
                  <span className="text-[10px] text-slate-500">{new Date(h.created_at).toLocaleDateString()}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
