apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: mqtt
      port: {{ .Values.service.mqtt.port | default 1883 }}
      targetPort: mqtt
      protocol: TCP
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
