apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: bolt
      port: {{ .Values.service.bolt.port | default 7687 }}
      targetPort: bolt
      protocol: TCP
    - name: http
      port: {{ .Values.service.http.port | default 7474 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "neo4j.selectorLabels" . | nindent 4 }}
