apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abenix-shared-code-assets
  namespace: abenix
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 20Gi
