'use client';

import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  Mail, Lock, ArrowRight, Eye, EyeOff, Shield, Zap,
  MapPin, TrendingUp, BarChart3, MessageSquare, Gauge, FileText,
  Building2, Palmtree, Globe, Users, Plane, Hotel,
  Mountain, Landmark, Star, Target, Sun, Waves,
} from 'lucide-react';

const API_URL = process.env.NEXT_PUBLIC_API_URL || '';
type Tab = 'login' | 'register';

const REGIONS = [
  { name: 'Riyadh', icon: Building2, gradient: 'from-green-500 to-green-700', desc: 'Business hub, entertainment capital, Riyadh Season', visitors: '4.2M' },
  { name: 'Makkah', icon: Landmark, gradient: 'from-green-600 to-emerald-800', desc: 'Holy city, Hajj & Umrah, spiritual tourism', visitors: '15.8M' },
  { name: 'Madinah', icon: Star, gradient: 'from-green-500 to-teal-700', desc: 'Prophet\'s Mosque, spiritual peace, cultural heritage', visitors: '8.5M' },
  { name: 'Jeddah', icon: Waves, gradient: 'from-green-400 to-green-700', desc: 'Red Sea coast, historic district, diving', visitors: '3.8M' },
  { name: 'NEOM', icon: Zap, gradient: 'from-green-500 to-emerald-600', desc: 'Future mega-city, Trojena ski, The Line', visitors: '0.35M' },
  { name: 'Al-Ula', icon: Mountain, gradient: 'from-green-600 to-green-800', desc: 'UNESCO Hegra, desert heritage, luxury resorts', visitors: '0.5M' },
];

const FEATURES = [
  { icon: BarChart3, title: 'Dashboard Analytics', desc: 'Real-time KPIs: visitors, revenue, occupancy, satisfaction across all regions', color: 'text-green-400', bg: 'bg-green-500/10' },
  { icon: MapPin, title: 'Regional Intelligence', desc: 'Per-region drilldowns with visitor trends, revenue, hotel capacity, and attractions', color: 'text-green-300', bg: 'bg-green-500/10' },
  { icon: TrendingUp, title: 'Deep Analytics', desc: 'Time series, visitor segmentation, revenue attribution, sentiment analysis', color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
  { icon: Gauge, title: 'What-If Simulations', desc: 'Visa policy, hotel capacity, seasonal planning, weather impact, competitor analysis', color: 'text-green-400', bg: 'bg-green-500/10' },
  { icon: MessageSquare, title: 'AI Chat', desc: 'Natural language Q&A over all your tourism datasets — powered by Abenix', color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
  { icon: FileText, title: 'Auto Reports', desc: 'Executive briefings, regional comparisons, segmentation reports generated by AI', color: 'text-green-300', bg: 'bg-green-500/10' },
];

const STATS = [
  { number: '27.4M', label: 'International visitors 2024', sub: 'Target: 70M by 2030' },
  { number: 'SAR 277B', label: 'Tourism revenue', sub: 'Target: SAR 750B by 2030' },
  { number: '9', label: 'Regions tracked', sub: 'Real-time analytics' },
  { number: '5', label: 'AI agents', sub: 'Powered by Abenix' },
];

export default function LandingPage() {
  const [tab, setTab] = useState<Tab>('login');
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [form, setForm] = useState({ email: '', password: '', full_name: '', organization: '' });
  const [showAuth, setShowAuth] = useState(false);

  function updateField(field: string, value: string) {
    setForm(prev => ({ ...prev, [field]: value }));
    setError('');
  }

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const endpoint = tab === 'register' ? '/api/st/auth/register' : '/api/st/auth/login';
      const body = tab === 'register'
        ? { email: form.email, password: form.password, full_name: form.full_name, organization: form.organization }
        : { email: form.email, password: form.password };
      const res = await fetch(`${API_URL}${endpoint}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
      const json = await res.json();
      if (json.error) { setError(typeof json.error === 'string' ? json.error : json.error.message || 'Authentication failed'); return; }
      if (json.data?.access_token) {
        localStorage.setItem('st_token', json.data.access_token);
        localStorage.setItem('st_refresh_token', json.data.refresh_token);
        localStorage.setItem('st_user', JSON.stringify(json.data.user));
        window.location.href = '/dashboard';
      }
    } catch { setError('Connection failed. Is the API running?'); } finally { setLoading(false); }
  }

  function fillDemo() {
    setForm({ ...form, email: 'test@sauditourism.gov.sa', password: 'TestPass123!' });
    setTab('login');
  }

  return (
    <div className="min-h-screen bg-[#021A0F] text-white overflow-x-hidden">
      {/* Background */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute inset-0" style={{
          backgroundImage: `
            radial-gradient(circle at 15% 20%, rgba(0,166,81,0.15), transparent 45%),
            radial-gradient(circle at 85% 60%, rgba(22,163,74,0.10), transparent 45%),
            radial-gradient(circle at 50% 100%, rgba(5,150,105,0.08), transparent 50%)
          `,
        }} />
        <div className="absolute inset-0 opacity-[0.02]" style={{
          backgroundImage: 'linear-gradient(to right, #00A651 1px, transparent 1px), linear-gradient(to bottom, #00A651 1px, transparent 1px)',
          backgroundSize: '48px 48px',
        }} />
      </div>

      {/* Nav */}
      <nav className="relative z-20 border-b border-green-900/40 backdrop-blur-sm bg-[#021A0F]/80">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-green-600/20 border border-green-500/30 flex items-center justify-center">
              <Palmtree className="w-6 h-6 text-green-400" />
            </div>
            <div>
              <div className="text-lg font-bold">Saudi Tourism Analytics</div>
              <div className="text-[10px] text-green-500/60 uppercase tracking-wider">Ministry of Tourism &middot; Vision 2030</div>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <a href="#features" className="text-xs text-green-300/50 hover:text-white transition-colors hidden sm:block">Features</a>
            <a href="#regions" className="text-xs text-green-300/50 hover:text-white transition-colors hidden sm:block">Regions</a>
            <button onClick={() => setShowAuth(true)}
              className="px-4 py-2 rounded-lg bg-gradient-to-r from-green-600 to-green-700 text-white text-xs font-semibold hover:shadow-lg hover:shadow-green-600/25 transition-all">
              Sign In
            </button>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 pt-20 pb-16">
        <div className="grid grid-cols-1 lg:grid-cols-[1.2fr_1fr] gap-12 items-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-green-600/10 border border-green-500/30 mb-6">
              <Globe className="w-3.5 h-3.5 text-green-400" />
              <span className="text-xs text-green-300 font-medium">Powered by Abenix &middot; 5 AI agents &middot; 10+ tools</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-bold leading-tight mb-6">
              Tourism Intelligence<br />
              <span className="bg-gradient-to-r from-green-400 via-emerald-400 to-green-300 bg-clip-text text-transparent">for the Kingdom.</span>
            </h1>
            <p className="text-lg text-green-100/60 leading-relaxed mb-8 max-w-2xl">
              Upload visitor data, hotel occupancy, revenue reports, and satisfaction surveys.
              AI agents analyze trends, run simulations, and generate executive briefings
              — helping the Ministry achieve <strong className="text-white">Vision 2030 tourism targets</strong>.
            </p>
            <div className="flex flex-wrap gap-4">
              <button onClick={() => setShowAuth(true)}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-green-600 to-green-700 text-white text-sm font-semibold hover:shadow-2xl hover:shadow-green-600/30 transition-all flex items-center gap-2">
                Get Started <ArrowRight className="w-4 h-4" />
              </button>
              <button onClick={() => { fillDemo(); setShowAuth(true); }}
                className="px-6 py-3 rounded-xl border border-green-700/50 text-green-200 text-sm font-semibold hover:border-green-500/50 hover:text-white transition-all">
                Try the Demo
              </button>
            </div>
            <div className="mt-10 flex flex-wrap items-center gap-6 text-xs text-green-400/40">
              <div className="flex items-center gap-1.5"><Shield className="w-3.5 h-3.5 text-green-500" /> Row-level RBAC</div>
              <div className="flex items-center gap-1.5"><Lock className="w-3.5 h-3.5 text-green-500" /> Secure data isolation</div>
              <div className="flex items-center gap-1.5"><Zap className="w-3.5 h-3.5 text-green-500" /> Real-time analytics</div>
            </div>
          </motion.div>

          {/* Stats card */}
          <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.6, delay: 0.2 }} className="relative">
            <div className="absolute inset-0 bg-gradient-to-br from-green-600/20 to-green-500/10 blur-3xl rounded-full" />
            <div className="relative rounded-2xl border border-green-800/50 bg-[#0A2818]/70 backdrop-blur-xl p-6 shadow-2xl">
              <div className="flex items-center gap-2 mb-4 pb-4 border-b border-green-800/50">
                <div className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
                <span className="text-[10px] uppercase tracking-wider text-green-400 font-semibold">Live Dashboard Preview</span>
              </div>
              <div className="grid grid-cols-2 gap-3">
                {STATS.map(s => (
                  <div key={s.label} className="rounded-xl bg-green-900/30 border border-green-800/30 p-4">
                    <div className="text-2xl font-bold bg-gradient-to-r from-green-300 to-emerald-300 bg-clip-text text-transparent">{s.number}</div>
                    <div className="text-[10px] text-green-300/50 mt-1 leading-tight">{s.label}</div>
                    <div className="text-[10px] text-green-400/30 mt-0.5">{s.sub}</div>
                  </div>
                ))}
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Regions */}
      <section id="regions" className="relative z-10 max-w-7xl mx-auto px-6 py-16 border-t border-green-900/40">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-green-600/10 border border-green-500/30 mb-4">
            <MapPin className="w-3.5 h-3.5 text-green-400" />
            <span className="text-xs text-green-300 font-medium">9 Regions Tracked</span>
          </div>
          <h2 className="text-3xl md:text-4xl font-bold mb-3">Every corner of the Kingdom</h2>
          <p className="text-green-200/40 max-w-2xl mx-auto">From the holy cities to NEOM, from mountain retreats to Red Sea resorts.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {REGIONS.map((r, idx) => (
            <motion.div key={r.name} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: idx * 0.05 }}
              className="group relative rounded-2xl border border-green-800/40 bg-[#0A2818]/30 backdrop-blur-sm p-6 hover:border-green-600/50 transition-all overflow-hidden">
              <div className={`absolute inset-0 bg-gradient-to-br ${r.gradient} opacity-0 group-hover:opacity-10 transition-opacity`} />
              <div className="relative">
                <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${r.gradient} flex items-center justify-center mb-4`}>
                  <r.icon className="w-6 h-6 text-white" />
                </div>
                <div className="flex items-center justify-between mb-2">
                  <h3 className="text-lg font-bold">{r.name}</h3>
                  <span className="text-xs text-green-400 font-mono">{r.visitors}</span>
                </div>
                <p className="text-xs text-green-200/40 leading-relaxed">{r.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section id="features" className="relative z-10 max-w-7xl mx-auto px-6 py-16 border-t border-green-900/40">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-3">AI-powered tourism intelligence</h2>
          <p className="text-green-200/40 max-w-2xl mx-auto">Every feature runs through Abenix agents with 10+ specialized tools. Zero local computation — pure agentic intelligence.</p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {FEATURES.map((f, idx) => (
            <motion.div key={f.title} initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: idx * 0.04 }}
              className="rounded-2xl border border-green-800/40 bg-[#0A2818]/30 backdrop-blur-sm p-5 hover:border-green-600/50 transition-all">
              <div className={`w-10 h-10 rounded-xl ${f.bg} border border-green-700/30 flex items-center justify-center mb-3`}>
                <f.icon className={`w-5 h-5 ${f.color}`} />
              </div>
              <h3 className="font-bold mb-1">{f.title}</h3>
              <p className="text-xs text-green-200/40 leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 py-20 border-t border-green-900/40">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}
          className="rounded-3xl border border-green-600/30 bg-gradient-to-br from-green-600/10 via-green-500/5 to-emerald-500/10 p-12 text-center">
          <Target className="w-10 h-10 text-green-400 mx-auto mb-4" />
          <h2 className="text-3xl md:text-4xl font-bold mb-3">Accelerate Vision 2030</h2>
          <p className="text-green-100/50 max-w-2xl mx-auto mb-8">
            150 million visits. SAR 750 billion revenue. 10% GDP contribution.
            Let AI analytics light the path to these targets.
          </p>
          <button onClick={() => setShowAuth(true)}
            className="px-8 py-3.5 rounded-xl bg-gradient-to-r from-green-600 to-green-700 text-white text-sm font-semibold hover:shadow-2xl hover:shadow-green-600/30 transition-all inline-flex items-center gap-2">
            Start Analyzing Now <ArrowRight className="w-4 h-4" />
          </button>
          <p className="text-[11px] text-green-400/30 mt-6">
            Demo: <code className="text-green-300">test@sauditourism.gov.sa</code> / <code className="text-green-300">TestPass123!</code>
          </p>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-green-900/40 py-8 text-center">
        <p className="text-xs text-green-400/30">
          Saudi Tourism Analytics &middot; Ministry of Tourism &middot; Kingdom of Saudi Arabia &middot;
          Built on <a href="http://localhost:3000" target="_blank" className="text-green-400 hover:text-green-300">Abenix</a>
        </p>
      </footer>

      {/* Auth modal */}
      {showAuth && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}
          className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4"
          onClick={(e) => { if (e.target === e.currentTarget) setShowAuth(false); }}>
          <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: 0.2 }} className="w-full max-w-md">
            <div className="bg-[#0A2818]/95 border border-green-700/40 rounded-2xl p-8 shadow-2xl">
              <div className="flex items-center justify-center gap-3 mb-6">
                <div className="w-12 h-12 rounded-xl bg-green-600/20 border border-green-500/30 flex items-center justify-center">
                  <Palmtree className="w-8 h-8 text-green-400" />
                </div>
                <div>
                  <h1 className="text-xl font-bold text-white">Saudi Tourism</h1>
                  <p className="text-xs text-green-400/50">Ministry of Tourism Analytics</p>
                </div>
              </div>

              <div className="flex border-b border-green-700/40 mb-6">
                {(['login', 'register'] as Tab[]).map(t => (
                  <button key={t} onClick={() => { setTab(t); setError(''); }}
                    className={`flex-1 pb-3 text-sm font-medium transition-colors ${tab === t ? 'text-green-400 border-b-2 border-green-400' : 'text-green-500/40 hover:text-green-300'}`}>
                    {t === 'login' ? 'Sign In' : 'Register'}
                  </button>
                ))}
              </div>

              <form onSubmit={handleSubmit} className="space-y-4">
                {tab === 'register' && (
                  <>
                    <div className="relative">
                      <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-green-600/50" />
                      <input type="text" value={form.full_name} onChange={e => updateField('full_name', e.target.value)}
                        placeholder="Full name" required
                        className="w-full bg-green-900/20 border border-green-700/40 rounded-lg pl-10 pr-4 py-3 text-white text-sm placeholder-green-600/40 focus:border-green-500 focus:outline-none transition-colors" />
                    </div>
                    <div className="relative">
                      <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-green-600/50" />
                      <input type="text" value={form.organization} onChange={e => updateField('organization', e.target.value)}
                        placeholder="Organization (optional)"
                        className="w-full bg-green-900/20 border border-green-700/40 rounded-lg pl-10 pr-4 py-3 text-white text-sm placeholder-green-600/40 focus:border-green-500 focus:outline-none transition-colors" />
                    </div>
                  </>
                )}
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-green-600/50" />
                  <input type="email" value={form.email} onChange={e => updateField('email', e.target.value)}
                    placeholder="Email address" required
                    className="w-full bg-green-900/20 border border-green-700/40 rounded-lg pl-10 pr-4 py-3 text-white text-sm placeholder-green-600/40 focus:border-green-500 focus:outline-none transition-colors" />
                </div>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-green-600/50" />
                  <input type={showPassword ? 'text' : 'password'} value={form.password} onChange={e => updateField('password', e.target.value)}
                    placeholder="Password" required
                    className="w-full bg-green-900/20 border border-green-700/40 rounded-lg pl-10 pr-10 py-3 text-white text-sm placeholder-green-600/40 focus:border-green-500 focus:outline-none transition-colors" />
                  <button type="button" onClick={() => setShowPassword(!showPassword)}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-green-600/50 hover:text-green-300">
                    {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  </button>
                </div>
                {error && <p className="text-red-400 text-xs text-center">{error}</p>}
                <button type="submit" disabled={loading}
                  className="w-full bg-gradient-to-r from-green-600 to-green-700 text-white font-semibold py-3 rounded-lg text-sm hover:shadow-lg hover:shadow-green-600/25 transition-all flex items-center justify-center gap-2 disabled:opacity-50">
                  {loading ? 'Loading...' : <>{tab === 'login' ? 'Sign In' : 'Create Account'} <ArrowRight className="w-4 h-4" /></>}
                </button>
              </form>
              {tab === 'login' && (
                <div className="mt-4 pt-4 border-t border-green-800/40 text-center">
                  <button onClick={fillDemo} className="text-[11px] text-green-500/40 hover:text-green-400 transition-colors">
                    Use demo credentials &rarr;
                  </button>
                </div>
              )}
              <button onClick={() => setShowAuth(false)} className="mt-4 w-full text-[11px] text-green-600/30 hover:text-green-400 text-center">Close</button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </div>
  );
}
