-- Generated by packages/db/generate_bootstrap_sql.py
-- Single-file schema snapshot for fresh installs.
--
-- Live deploys do NOT run this file directly. They run
-- packages/db/bootstrap.py which calls Base.metadata.create_all()
-- against the DB engine — the same source of truth, programmatically.
-- Use this file for human inspection, code review, and as a
-- portable schema reference for downstream consumers.
--
-- After install, alembic is stamped at heads so future schema
-- changes go through `alembic upgrade heads` as usual.

BEGIN;

-- mcp_registry_cache
CREATE TABLE mcp_registry_cache (
	registry_id VARCHAR(255) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description TEXT NOT NULL, 
	server_url VARCHAR(1000) NOT NULL, 
	auth_type VARCHAR(50) NOT NULL, 
	categories TEXT[], 
	tools_count INTEGER NOT NULL, 
	popularity_score INTEGER NOT NULL, 
	verified BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_mcp_registry_cache_registry_id ON mcp_registry_cache (registry_id);

-- tenants
CREATE TABLE tenants (
	name VARCHAR(255) NOT NULL, 
	slug VARCHAR(255) NOT NULL, 
	plan tenant_plan NOT NULL, 
	stripe_customer_id VARCHAR(255), 
	settings JSONB, 
	slack_webhook_url TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	daily_cost_limit NUMERIC(10, 2), 
	monthly_cost_limit NUMERIC(10, 2), 
	id UUID NOT NULL, 
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_tenants_slug ON tenants (slug);

-- activity_logs
CREATE TABLE activity_logs (
	user_id UUID NOT NULL, 
	action VARCHAR(100) NOT NULL, 
	details JSONB, 
	ip_address VARCHAR(45), 
	user_agent VARCHAR(500), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_activity_logs_tenant_id ON activity_logs (tenant_id);
CREATE INDEX ix_activity_logs_user_id ON activity_logs (user_id);

-- connectors
CREATE TABLE connectors (
	name VARCHAR(255) NOT NULL, 
	kind connector_kind NOT NULL, 
	preset_key VARCHAR(128), 
	base_url VARCHAR(1000) NOT NULL, 
	auth_type connector_auth_type NOT NULL, 
	secret_ref UUID, 
	config JSONB, 
	is_active BOOLEAN NOT NULL, 
	last_test_at TIMESTAMP WITH TIME ZONE, 
	last_test_ok BOOLEAN, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_connectors_tenant_id ON connectors (tenant_id);
CREATE INDEX ix_connectors_kind ON connectors (kind);

-- users
CREATE TABLE users (
	email VARCHAR(255) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	full_name VARCHAR(255) NOT NULL, 
	avatar_url VARCHAR(500), 
	role user_role NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	stripe_connect_id VARCHAR(255), 
	stripe_connect_onboarded BOOLEAN NOT NULL, 
	notification_settings JSONB, 
	token_monthly_allowance INTEGER, 
	tokens_used_this_month INTEGER NOT NULL, 
	cost_monthly_limit NUMERIC(10, 2), 
	cost_used_this_month NUMERIC(10, 4) NOT NULL, 
	quota_reset_at TIMESTAMP WITH TIME ZONE, 
	voice_id VARCHAR(120), 
	voice_provider VARCHAR(40), 
	voice_consent_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE INDEX ix_users_tenant_id ON users (tenant_id);

-- webhooks
CREATE TABLE webhooks (
	url VARCHAR(1000) NOT NULL, 
	signing_secret VARCHAR(255), 
	events JSONB, 
	is_active BOOLEAN NOT NULL, 
	failure_count INTEGER NOT NULL, 
	last_delivery_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_webhooks_tenant_id ON webhooks (tenant_id);

-- workspaces
CREATE TABLE workspaces (
	name VARCHAR(255) NOT NULL, 
	slug VARCHAR(255) NOT NULL, 
	description VARCHAR(1000), 
	settings JSONB, 
	is_default BOOLEAN NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_workspaces_slug ON workspaces (slug);
CREATE INDEX ix_workspaces_tenant_id ON workspaces (tenant_id);

-- agents
CREATE TABLE agents (
	creator_id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	slug VARCHAR(255) NOT NULL, 
	description TEXT NOT NULL, 
	system_prompt TEXT NOT NULL, 
	model_config JSONB NOT NULL, 
	agent_type agent_type NOT NULL, 
	category VARCHAR(100), 
	is_published BOOLEAN NOT NULL, 
	marketplace_price NUMERIC(10, 2), 
	version VARCHAR(50) NOT NULL, 
	icon_url VARCHAR(500), 
	status agent_status NOT NULL, 
	rejection_reason TEXT, 
	version_tag VARCHAR(50), 
	traffic_weight NUMERIC(5, 2) DEFAULT '100', 
	parent_agent_id UUID, 
	per_execution_cost_limit NUMERIC(10, 4), 
	daily_cost_limit NUMERIC(10, 2), 
	runtime_pool VARCHAR(40) DEFAULT 'default' NOT NULL, 
	min_replicas INTEGER DEFAULT '1' NOT NULL, 
	max_replicas INTEGER DEFAULT '10' NOT NULL, 
	concurrency_per_replica INTEGER DEFAULT '3' NOT NULL, 
	rate_limit_qps INTEGER, 
	daily_budget_usd NUMERIC(10, 2), 
	dedicated_mode BOOLEAN DEFAULT 'false' NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(creator_id) REFERENCES users (id), 
	FOREIGN KEY(parent_agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_agents_status ON agents (tenant_id, status);
CREATE INDEX ix_agents_tenant_id ON agents (tenant_id);
CREATE INDEX ix_agents_slug ON agents (slug);
CREATE INDEX ix_agents_tenant_created ON agents (tenant_id, created_at);
CREATE INDEX ix_agents_creator_id ON agents (creator_id);

-- api_keys
CREATE TABLE api_keys (
	user_id UUID NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	key_hash VARCHAR(255) NOT NULL, 
	key_prefix VARCHAR(20) NOT NULL, 
	last_used_at TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN NOT NULL, 
	scopes JSONB, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	max_monthly_tokens INTEGER, 
	tokens_used INTEGER NOT NULL, 
	max_monthly_cost NUMERIC(10, 2), 
	cost_used NUMERIC(10, 4) NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_api_keys_tenant_id ON api_keys (tenant_id);
CREATE INDEX ix_api_keys_user_id ON api_keys (user_id);

-- code_assets
CREATE TABLE code_assets (
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	source_type code_asset_source NOT NULL, 
	source_git_url VARCHAR(1000), 
	source_ref VARCHAR(255), 
	storage_uri VARCHAR(1000), 
	file_size_bytes INTEGER, 
	detected_language VARCHAR(50), 
	detected_version VARCHAR(50), 
	detected_package_manager VARCHAR(50), 
	detected_entrypoint VARCHAR(500), 
	suggested_image VARCHAR(255), 
	suggested_build_command TEXT, 
	suggested_run_command TEXT, 
	analysis_notes JSONB, 
	input_schema JSONB, 
	output_schema JSONB, 
	status code_asset_status NOT NULL, 
	error TEXT, 
	last_test_input JSONB, 
	last_test_output JSONB, 
	last_test_at TIMESTAMP WITH TIME ZONE, 
	last_test_ok BOOLEAN, 
	created_by UUID, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_code_assets_status ON code_assets (status);
CREATE INDEX ix_code_assets_tenant_id ON code_assets (tenant_id);
CREATE INDEX ix_code_assets_tenant_name ON code_assets (tenant_id, name);

-- knowledge_projects
CREATE TABLE knowledge_projects (
	name VARCHAR(255) NOT NULL, 
	slug VARCHAR(120) NOT NULL, 
	description TEXT NOT NULL, 
	ontology_schema_id UUID, 
	created_by UUID NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_kproj_tenant_slug UNIQUE (tenant_id, slug), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_knowledge_projects_tenant_id ON knowledge_projects (tenant_id);
CREATE INDEX ix_kproj_tenant_created ON knowledge_projects (tenant_id, created_at);

-- ml_models
CREATE TABLE ml_models (
	name VARCHAR(255) NOT NULL, 
	version VARCHAR(50) NOT NULL, 
	framework ml_model_framework NOT NULL, 
	description TEXT, 
	file_uri VARCHAR(1000) NOT NULL, 
	file_size_bytes INTEGER, 
	original_filename VARCHAR(500), 
	input_schema JSONB, 
	output_schema JSONB, 
	status ml_model_status NOT NULL, 
	training_metrics JSONB, 
	tags JSONB, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	created_by UUID, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_ml_models_status ON ml_models (status);
CREATE INDEX ix_ml_models_tenant_name ON ml_models (tenant_id, name);
CREATE INDEX ix_ml_models_tenant_id ON ml_models (tenant_id);

-- moderation_policies
CREATE TABLE moderation_policies (
	name VARCHAR(255) NOT NULL, 
	description TEXT, 
	is_active BOOLEAN DEFAULT 'true' NOT NULL, 
	pre_llm BOOLEAN DEFAULT 'true' NOT NULL, 
	post_llm BOOLEAN DEFAULT 'true' NOT NULL, 
	on_tool_output BOOLEAN DEFAULT 'false' NOT NULL, 
	provider VARCHAR(40) DEFAULT 'openai' NOT NULL, 
	provider_model VARCHAR(80) DEFAULT 'omni-moderation-latest' NOT NULL, 
	thresholds JSONB DEFAULT '{}' NOT NULL, 
	default_threshold FLOAT DEFAULT '0.5' NOT NULL, 
	category_actions JSONB DEFAULT '{}' NOT NULL, 
	default_action moderation_action DEFAULT 'block' NOT NULL, 
	custom_patterns JSONB DEFAULT '[]' NOT NULL, 
	redaction_mask VARCHAR(40) DEFAULT '█████' NOT NULL, 
	created_by UUID, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_moderation_policies_tenant_active ON moderation_policies (tenant_id, is_active);
CREATE INDEX ix_moderation_policies_tenant_id ON moderation_policies (tenant_id);

-- notifications
CREATE TABLE notifications (
	user_id UUID NOT NULL, 
	type VARCHAR(50) NOT NULL, 
	title VARCHAR(255) NOT NULL, 
	message TEXT NOT NULL, 
	is_read BOOLEAN NOT NULL, 
	link VARCHAR(500), 
	metadata JSONB, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_notifications_user_unread ON notifications (user_id, is_read);
CREATE INDEX ix_notifications_tenant_id ON notifications (tenant_id);
CREATE INDEX ix_notifications_user_id ON notifications (user_id);

-- resource_shares
CREATE TABLE resource_shares (
	resource_type VARCHAR(64) NOT NULL, 
	resource_id UUID NOT NULL, 
	shared_with_user_id UUID, 
	shared_with_email VARCHAR(255), 
	permission share_permission NOT NULL, 
	shared_by UUID NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_resource_share_recipient UNIQUE (resource_type, resource_id, shared_with_user_id), 
	FOREIGN KEY(shared_with_user_id) REFERENCES users (id), 
	FOREIGN KEY(shared_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_resource_shares_tenant_id ON resource_shares (tenant_id);
CREATE INDEX ix_resource_shares_recipient ON resource_shares (shared_with_user_id);
CREATE INDEX ix_resource_shares_resource ON resource_shares (resource_type, resource_id);

-- saved_tools
CREATE TABLE saved_tools (
	name VARCHAR(100) NOT NULL, 
	description TEXT NOT NULL, 
	code TEXT NOT NULL, 
	input_schema JSONB NOT NULL, 
	created_by UUID NOT NULL, 
	approved_by UUID, 
	status VARCHAR(20) NOT NULL, 
	is_public BOOLEAN NOT NULL, 
	usage_count INTEGER NOT NULL, 
	review_score FLOAT, 
	review_notes TEXT, 
	permissions JSONB NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_saved_tool_tenant_name UNIQUE (tenant_id, name), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(approved_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_saved_tools_tenant_id ON saved_tools (tenant_id);
CREATE INDEX ix_saved_tool_status ON saved_tools (tenant_id, status);

-- team_invites
CREATE TABLE team_invites (
	invited_by UUID NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	role VARCHAR(50) NOT NULL, 
	status invite_status NOT NULL, 
	token VARCHAR(255) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(invited_by) REFERENCES users (id), 
	UNIQUE (token), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_team_invites_email ON team_invites (email);
CREATE INDEX ix_team_invites_tenant_id ON team_invites (tenant_id);

-- user_mcp_connections
CREATE TABLE user_mcp_connections (
	user_id UUID NOT NULL, 
	server_name VARCHAR(255) NOT NULL, 
	server_url VARCHAR(1000) NOT NULL, 
	transport_type VARCHAR(50) NOT NULL, 
	auth_type VARCHAR(50) NOT NULL, 
	auth_config JSONB, 
	discovered_tools JSONB, 
	health_status VARCHAR(50) NOT NULL, 
	is_enabled BOOLEAN NOT NULL, 
	last_health_check TIMESTAMP WITH TIME ZONE, 
	oauth2_client_id VARCHAR(255), 
	oauth2_authorization_url VARCHAR(1000), 
	oauth2_token_url VARCHAR(1000), 
	oauth2_access_token_enc TEXT, 
	oauth2_refresh_token_enc TEXT, 
	oauth2_token_expires_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_user_mcp_connections_tenant_id ON user_mcp_connections (tenant_id);
CREATE INDEX ix_user_mcp_connections_user_id ON user_mcp_connections (user_id);
CREATE INDEX ix_mcp_conn_tenant_user ON user_mcp_connections (tenant_id, user_id);

-- webhook_deliveries
CREATE TABLE webhook_deliveries (
	webhook_id UUID NOT NULL, 
	event VARCHAR(100) NOT NULL, 
	request_payload JSONB, 
	response_status_code INTEGER, 
	response_body TEXT, 
	delivered BOOLEAN, 
	attempts INTEGER, 
	delivery_id VARCHAR(100), 
	error_message TEXT, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(webhook_id) REFERENCES webhooks (id) ON DELETE CASCADE, 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_webhook_deliveries_webhook_id ON webhook_deliveries (webhook_id);
CREATE INDEX ix_webhook_deliveries_tenant_id ON webhook_deliveries (tenant_id);

-- agent_favorites
CREATE TABLE agent_favorites (
	user_id UUID NOT NULL, 
	agent_id UUID NOT NULL, 
	collection VARCHAR(100), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id)
);

CREATE INDEX ix_agent_favorites_agent_id ON agent_favorites (agent_id);
CREATE INDEX ix_agent_favorites_user_id ON agent_favorites (user_id);

-- agent_mcp_tools
CREATE TABLE agent_mcp_tools (
	agent_id UUID NOT NULL, 
	mcp_connection_id UUID NOT NULL, 
	tool_name VARCHAR(255) NOT NULL, 
	tool_config JSONB, 
	approval_required BOOLEAN NOT NULL, 
	max_calls_per_execution INTEGER, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(mcp_connection_id) REFERENCES user_mcp_connections (id)
);

CREATE INDEX ix_agent_mcp_tools_agent ON agent_mcp_tools (agent_id, mcp_connection_id);
CREATE INDEX ix_agent_mcp_tools_mcp_connection_id ON agent_mcp_tools (mcp_connection_id);
CREATE INDEX ix_agent_mcp_tools_agent_id ON agent_mcp_tools (agent_id);

-- agent_memories
CREATE TABLE agent_memories (
	agent_id UUID NOT NULL, 
	key VARCHAR(500) NOT NULL, 
	value TEXT NOT NULL, 
	memory_type memory_type NOT NULL, 
	importance INTEGER NOT NULL, 
	access_count INTEGER NOT NULL, 
	metadata JSONB, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_agent_memories_agent_type ON agent_memories (agent_id, memory_type);
CREATE INDEX ix_agent_memories_tenant_agent ON agent_memories (tenant_id, agent_id);
CREATE INDEX ix_agent_memories_agent_id ON agent_memories (agent_id);
CREATE INDEX ix_agent_memories_tenant_id ON agent_memories (tenant_id);
CREATE INDEX ix_agent_memories_agent_key ON agent_memories (agent_id, key);

-- agent_revisions
CREATE TABLE agent_revisions (
	agent_id UUID NOT NULL, 
	revision_number INTEGER NOT NULL, 
	changed_by UUID NOT NULL, 
	change_type VARCHAR(50) NOT NULL, 
	previous_state JSONB, 
	new_state JSONB, 
	diff_summary TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(changed_by) REFERENCES users (id)
);

CREATE INDEX ix_agent_revisions_agent_id ON agent_revisions (agent_id);

-- agent_shares
CREATE TABLE agent_shares (
	agent_id UUID NOT NULL, 
	shared_with_user_id UUID, 
	shared_with_email VARCHAR(255), 
	permission share_permission NOT NULL, 
	shared_by UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(shared_with_user_id) REFERENCES users (id), 
	FOREIGN KEY(shared_by) REFERENCES users (id)
);

CREATE INDEX ix_agent_shares_shared_with_user_id ON agent_shares (shared_with_user_id);
CREATE INDEX ix_agent_shares_agent_id ON agent_shares (agent_id);

-- agent_triggers
CREATE TABLE agent_triggers (
	agent_id UUID NOT NULL, 
	created_by UUID NOT NULL, 
	trigger_type VARCHAR(20) NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	webhook_token VARCHAR(64), 
	cron_expression VARCHAR(100), 
	next_run_at TIMESTAMP WITH TIME ZONE, 
	last_run_at TIMESTAMP WITH TIME ZONE, 
	is_active BOOLEAN NOT NULL, 
	default_message VARCHAR(2000), 
	default_context JSONB, 
	run_count INTEGER NOT NULL, 
	last_status VARCHAR(20), 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	UNIQUE (webhook_token), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_agent_triggers_agent_id ON agent_triggers (agent_id);
CREATE INDEX ix_agent_triggers_tenant_id ON agent_triggers (tenant_id);

-- batch_jobs
CREATE TABLE batch_jobs (
	agent_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	total_inputs INTEGER NOT NULL, 
	completed_count INTEGER NOT NULL, 
	failed_count INTEGER NOT NULL, 
	results JSONB, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_batch_jobs_tenant_id ON batch_jobs (tenant_id);

-- conversations
CREATE TABLE conversations (
	user_id UUID NOT NULL, 
	agent_id UUID, 
	agent_slug VARCHAR(128), 
	app_slug VARCHAR(64), 
	subject_type VARCHAR(40), 
	subject_id VARCHAR(128), 
	title VARCHAR(255) NOT NULL, 
	model_used VARCHAR(100), 
	is_archived BOOLEAN NOT NULL, 
	is_shared BOOLEAN NOT NULL, 
	share_token VARCHAR(64), 
	total_tokens INTEGER NOT NULL, 
	total_cost NUMERIC(10, 6) NOT NULL, 
	message_count INTEGER NOT NULL, 
	last_message_preview TEXT, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	UNIQUE (share_token), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_conversations_tenant_id ON conversations (tenant_id);
CREATE INDEX ix_conversations_user_id ON conversations (user_id);
CREATE INDEX ix_conversations_user_updated ON conversations (user_id, updated_at);
CREATE INDEX ix_conversations_app_subject ON conversations (app_slug, subject_type, subject_id, updated_at);
CREATE INDEX ix_conversations_app_slug ON conversations (app_slug);

-- executions
CREATE TABLE executions (
	agent_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	input_message TEXT NOT NULL, 
	output_message TEXT, 
	status execution_status NOT NULL, 
	input_tokens INTEGER, 
	output_tokens INTEGER, 
	cost NUMERIC(10, 6), 
	anthropic_cost NUMERIC(10, 6) NOT NULL, 
	openai_cost NUMERIC(10, 6) NOT NULL, 
	google_cost NUMERIC(10, 6) NOT NULL, 
	other_cost NUMERIC(10, 6) NOT NULL, 
	model_used VARCHAR(100), 
	duration_ms INTEGER, 
	tool_calls JSONB, 
	node_results JSONB, 
	error_message TEXT, 
	failure_code VARCHAR(64), 
	started_at TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	confidence_score NUMERIC(3, 2), 
	execution_trace JSONB, 
	parent_execution_id UUID, 
	retry_count INTEGER, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(parent_execution_id) REFERENCES executions (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_executions_user_agent ON executions (user_id, agent_id);
CREATE INDEX ix_executions_agent_id ON executions (agent_id);
CREATE INDEX ix_executions_tenant_created ON executions (tenant_id, created_at);
CREATE INDEX ix_executions_agent_status ON executions (agent_id, status);
CREATE INDEX ix_executions_tenant_id ON executions (tenant_id);
CREATE INDEX ix_executions_failure_code ON executions (failure_code);
CREATE INDEX ix_executions_user_id ON executions (user_id);

-- knowledge_collections
CREATE TABLE knowledge_collections (
	project_id UUID, 
	default_visibility collection_visibility NOT NULL, 
	agent_id UUID, 
	created_by UUID, 
	name VARCHAR(255) NOT NULL, 
	description TEXT NOT NULL, 
	embedding_model VARCHAR(100) NOT NULL, 
	chunk_size INTEGER NOT NULL, 
	chunk_overlap INTEGER NOT NULL, 
	vector_backend VARCHAR(20) NOT NULL, 
	status kb_status NOT NULL, 
	doc_count INTEGER NOT NULL, 
	graph_enabled BOOLEAN NOT NULL, 
	entity_count INTEGER NOT NULL, 
	relationship_count INTEGER NOT NULL, 
	last_cognified_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES knowledge_projects (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(created_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_knowledge_collections_agent_id ON knowledge_collections (agent_id);
CREATE INDEX ix_kb_tenant_created ON knowledge_collections (tenant_id, created_at);
CREATE INDEX ix_knowledge_collections_tenant_id ON knowledge_collections (tenant_id);
CREATE INDEX ix_kb_project ON knowledge_collections (project_id);

-- meetings
CREATE TABLE meetings (
	user_id UUID NOT NULL, 
	agent_id UUID, 
	title VARCHAR(300) NOT NULL, 
	provider VARCHAR(20) NOT NULL, 
	room VARCHAR(500) NOT NULL, 
	join_url VARCHAR(1000), 
	scheduled_at TIMESTAMP WITH TIME ZONE, 
	started_at TIMESTAMP WITH TIME ZONE, 
	ended_at TIMESTAMP WITH TIME ZONE, 
	status VARCHAR(30) NOT NULL, 
	scope_allow TEXT[], 
	scope_defer TEXT[], 
	persona_scopes TEXT[], 
	display_name VARCHAR(200) NOT NULL, 
	summary TEXT, 
	transcript_count INTEGER NOT NULL, 
	decision_count INTEGER NOT NULL, 
	deferral_count INTEGER NOT NULL, 
	notes JSONB, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_meetings_tenant_id ON meetings (tenant_id);
CREATE INDEX ix_meetings_user_id ON meetings (user_id);
CREATE INDEX ix_meetings_user_status ON meetings (user_id, status);
CREATE INDEX ix_meetings_agent_id ON meetings (agent_id);
CREATE INDEX ix_meetings_status ON meetings (status);
CREATE INDEX ix_meetings_scheduled ON meetings (scheduled_at);

-- ml_model_deployments
CREATE TABLE ml_model_deployments (
	model_id UUID NOT NULL, 
	deployment_type deployment_type NOT NULL, 
	endpoint_url VARCHAR(500), 
	replicas INTEGER NOT NULL, 
	status deployment_status NOT NULL, 
	pod_name VARCHAR(255), 
	service_name VARCHAR(255), 
	k8s_namespace VARCHAR(100) NOT NULL, 
	config JSONB, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(model_id) REFERENCES ml_models (id) ON DELETE CASCADE
);

CREATE INDEX ix_ml_deployments_status ON ml_model_deployments (status);
CREATE INDEX ix_ml_deployments_model ON ml_model_deployments (model_id);

-- moderation_events
CREATE TABLE moderation_events (
	policy_id UUID, 
	user_id UUID, 
	execution_id UUID, 
	source VARCHAR(40) NOT NULL, 
	outcome moderation_event_outcome NOT NULL, 
	content_sha256 VARCHAR(64), 
	content_preview VARCHAR(500), 
	provider_response JSONB DEFAULT '{}' NOT NULL, 
	acted_categories JSONB DEFAULT '[]' NOT NULL, 
	latency_ms INTEGER DEFAULT '0' NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(policy_id) REFERENCES moderation_policies (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_moderation_events_tenant_created ON moderation_events (tenant_id, created_at);
CREATE INDEX ix_moderation_events_tenant_id ON moderation_events (tenant_id);
CREATE INDEX ix_moderation_events_execution ON moderation_events (execution_id);
CREATE INDEX ix_moderation_events_outcome ON moderation_events (outcome);

-- ontology_schemas
CREATE TABLE ontology_schemas (
	project_id UUID NOT NULL, 
	version INTEGER NOT NULL, 
	name VARCHAR(255) NOT NULL, 
	description VARCHAR(2000) NOT NULL, 
	entity_types JSONB NOT NULL, 
	relationship_types JSONB NOT NULL, 
	created_by UUID, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_ontology_proj_version UNIQUE (project_id, version), 
	FOREIGN KEY(project_id) REFERENCES knowledge_projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by) REFERENCES users (id)
);

CREATE INDEX ix_ontology_schemas_project ON ontology_schemas (project_id);

-- pipeline_states
CREATE TABLE pipeline_states (
	agent_id UUID NOT NULL, 
	key VARCHAR(255) NOT NULL, 
	value JSONB NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_pipeline_state_agent_key UNIQUE (agent_id, key), 
	FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_pipeline_state_agent ON pipeline_states (agent_id);
CREATE INDEX ix_pipeline_states_tenant_id ON pipeline_states (tenant_id);

-- project_members
CREATE TABLE project_members (
	project_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	role project_role NOT NULL, 
	granted_by UUID, 
	granted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_project_member UNIQUE (project_id, user_id), 
	FOREIGN KEY(project_id) REFERENCES knowledge_projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(granted_by) REFERENCES users (id)
);

CREATE INDEX ix_project_members_project ON project_members (project_id);
CREATE INDEX ix_project_members_user ON project_members (user_id);

-- reviews
CREATE TABLE reviews (
	agent_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	rating INTEGER NOT NULL, 
	comment TEXT, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE INDEX ix_reviews_agent ON reviews (agent_id, created_at);
CREATE INDEX ix_reviews_user_agent ON reviews (user_id, agent_id);
CREATE INDEX ix_reviews_agent_id ON reviews (agent_id);
CREATE INDEX ix_reviews_user_id ON reviews (user_id);

-- subscriptions
CREATE TABLE subscriptions (
	user_id UUID NOT NULL, 
	agent_id UUID NOT NULL, 
	stripe_subscription_id VARCHAR(255), 
	stripe_payment_intent_id VARCHAR(255), 
	plan_type VARCHAR(50) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	current_period_end TIMESTAMP WITH TIME ZONE, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id)
);

CREATE INDEX ix_subscriptions_user_id ON subscriptions (user_id);
CREATE INDEX ix_subscriptions_agent_id ON subscriptions (agent_id);
CREATE INDEX ix_subscriptions_user_agent ON subscriptions (user_id, agent_id);

-- usage_records
CREATE TABLE usage_records (
	user_id UUID NOT NULL, 
	agent_id UUID, 
	record_type record_type NOT NULL, 
	quantity NUMERIC(16, 4) NOT NULL, 
	unit VARCHAR(50) NOT NULL, 
	cost NUMERIC(10, 6) NOT NULL, 
	metadata JSONB, 
	period_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	period_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_usage_user_type ON usage_records (user_id, record_type);
CREATE INDEX ix_usage_records_tenant_id ON usage_records (tenant_id);
CREATE INDEX ix_usage_records_agent_id ON usage_records (agent_id);
CREATE INDEX ix_usage_records_user_id ON usage_records (user_id);
CREATE INDEX ix_usage_tenant_created ON usage_records (tenant_id, created_at);

-- agent_collection_grants
CREATE TABLE agent_collection_grants (
	agent_id UUID NOT NULL, 
	collection_id UUID NOT NULL, 
	permission collection_permission NOT NULL, 
	granted_by UUID, 
	granted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_agent_collection_grant UNIQUE (agent_id, collection_id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	FOREIGN KEY(collection_id) REFERENCES knowledge_collections (id) ON DELETE CASCADE, 
	FOREIGN KEY(granted_by) REFERENCES users (id)
);

CREATE INDEX ix_agent_collection_grants_agent ON agent_collection_grants (agent_id);
CREATE INDEX ix_agent_collection_grants_collection ON agent_collection_grants (collection_id);

-- agent_comments
CREATE TABLE agent_comments (
	agent_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	revision_id UUID, 
	parent_id UUID, 
	content TEXT NOT NULL, 
	is_resolved BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(revision_id) REFERENCES agent_revisions (id), 
	FOREIGN KEY(parent_id) REFERENCES agent_comments (id)
);

CREATE INDEX ix_agent_comments_agent_id ON agent_comments (agent_id);

-- approvals
CREATE TABLE approvals (
	agent_id UUID, 
	agent_execution_id UUID, 
	title VARCHAR(255) NOT NULL, 
	payload JSONB, 
	required_signoffs INTEGER NOT NULL, 
	signoffs JSONB, 
	status approval_status NOT NULL, 
	requested_by UUID, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	client_token VARCHAR(120), 
	gate_kind VARCHAR(120), 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(agent_execution_id) REFERENCES executions (id), 
	FOREIGN KEY(requested_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_approvals_gate_kind ON approvals (gate_kind);
CREATE INDEX ix_approvals_status ON approvals (status);
CREATE INDEX ix_approvals_agent_execution_id ON approvals (agent_execution_id);
CREATE INDEX ix_approvals_agent_id ON approvals (agent_id);
CREATE INDEX ix_approvals_tenant_id ON approvals (tenant_id);

-- cognify_jobs
CREATE TABLE cognify_jobs (
	kb_id UUID NOT NULL, 
	status cognify_status NOT NULL, 
	documents_processed INTEGER NOT NULL, 
	entities_extracted INTEGER NOT NULL, 
	entities_merged INTEGER NOT NULL, 
	relationships_extracted INTEGER NOT NULL, 
	tokens_used INTEGER NOT NULL, 
	cost_usd NUMERIC(10, 6) NOT NULL, 
	anthropic_cost NUMERIC(10, 6) NOT NULL, 
	openai_cost NUMERIC(10, 6) NOT NULL, 
	google_cost NUMERIC(10, 6) NOT NULL, 
	other_cost NUMERIC(10, 6) NOT NULL, 
	duration_seconds NUMERIC(10, 2), 
	error_message TEXT, 
	config JSONB, 
	started_at TIMESTAMP WITH TIME ZONE, 
	completed_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_cognify_jobs_kb_id ON cognify_jobs (kb_id);
CREATE INDEX ix_cognify_jobs_tenant_created ON cognify_jobs (tenant_id, created_at);
CREATE INDEX ix_cognify_jobs_kb_status ON cognify_jobs (kb_id, status);
CREATE INDEX ix_cognify_jobs_tenant_id ON cognify_jobs (tenant_id);

-- dead_letter_executions
CREATE TABLE dead_letter_executions (
	execution_id UUID NOT NULL, 
	agent_id UUID, 
	failure_code VARCHAR(80) NOT NULL, 
	error_message VARCHAR(2000), 
	original_input JSONB, 
	replay_count INTEGER NOT NULL, 
	last_replay_at TIMESTAMP WITH TIME ZONE, 
	resolved BOOLEAN NOT NULL, 
	replay_execution_id UUID, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(execution_id) REFERENCES executions (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(replay_execution_id) REFERENCES executions (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE UNIQUE INDEX ix_dead_letter_executions_execution_id ON dead_letter_executions (execution_id);
CREATE INDEX ix_dead_letter_executions_tenant_id ON dead_letter_executions (tenant_id);
CREATE INDEX ix_dead_letter_executions_agent_id ON dead_letter_executions (agent_id);

-- documents
CREATE TABLE documents (
	kb_id UUID NOT NULL, 
	filename VARCHAR(500) NOT NULL, 
	file_type VARCHAR(50) NOT NULL, 
	file_size INTEGER NOT NULL, 
	chunk_count INTEGER NOT NULL, 
	status document_status NOT NULL, 
	storage_url VARCHAR(1000) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id)
);

CREATE INDEX ix_documents_kb_id ON documents (kb_id);
CREATE INDEX ix_documents_kb_status ON documents (kb_id, status);

-- drift_alerts
CREATE TABLE drift_alerts (
	agent_id UUID NOT NULL, 
	execution_id UUID, 
	severity VARCHAR(20) NOT NULL, 
	metric VARCHAR(100) NOT NULL, 
	baseline_value FLOAT NOT NULL, 
	current_value FLOAT NOT NULL, 
	deviation_pct FLOAT NOT NULL, 
	acknowledged BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id) ON DELETE CASCADE, 
	FOREIGN KEY(execution_id) REFERENCES executions (id) ON DELETE SET NULL, 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_drift_alert_tenant_created ON drift_alerts (tenant_id, created_at);
CREATE INDEX ix_drift_alert_agent ON drift_alerts (agent_id);
CREATE INDEX ix_drift_alerts_tenant_id ON drift_alerts (tenant_id);

-- execution_idempotency
CREATE TABLE execution_idempotency (
	key VARCHAR(255) NOT NULL, 
	agent_id UUID, 
	execution_id UUID, 
	status VARCHAR(40) NOT NULL, 
	cached_response JSONB, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_idempotency_tenant_key UNIQUE (tenant_id, key), 
	FOREIGN KEY(agent_id) REFERENCES agents (id), 
	FOREIGN KEY(execution_id) REFERENCES executions (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_execution_idempotency_expires_at ON execution_idempotency (expires_at);
CREATE INDEX ix_execution_idempotency_agent_id ON execution_idempotency (agent_id);
CREATE INDEX ix_execution_idempotency_key ON execution_idempotency (key);
CREATE INDEX ix_execution_idempotency_tenant_id ON execution_idempotency (tenant_id);

-- graph_entities
CREATE TABLE graph_entities (
	kb_id UUID NOT NULL, 
	canonical_name VARCHAR(500) NOT NULL, 
	entity_type VARCHAR(100) NOT NULL, 
	description TEXT, 
	aliases JSONB, 
	properties JSONB, 
	source_doc_ids JSONB, 
	neo4j_node_id VARCHAR(100), 
	embedding_id VARCHAR(200), 
	mention_count INTEGER NOT NULL, 
	access_count INTEGER NOT NULL, 
	confidence NUMERIC(5, 4) NOT NULL, 
	last_accessed_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_graph_entities_kb_id ON graph_entities (kb_id);
CREATE UNIQUE INDEX ix_graph_entities_kb_name ON graph_entities (kb_id, canonical_name);
CREATE INDEX ix_graph_entities_kb_type ON graph_entities (kb_id, entity_type);
CREATE INDEX ix_graph_entities_tenant_id ON graph_entities (tenant_id);

-- meeting_deferrals
CREATE TABLE meeting_deferrals (
	meeting_id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	question TEXT NOT NULL, 
	context TEXT, 
	answer TEXT, 
	status VARCHAR(20) NOT NULL, 
	answered_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(meeting_id) REFERENCES meetings (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_meeting_deferrals_meeting_id ON meeting_deferrals (meeting_id);
CREATE INDEX ix_meeting_deferrals_tenant_id ON meeting_deferrals (tenant_id);
CREATE INDEX ix_meeting_deferrals_meeting ON meeting_deferrals (meeting_id, created_at);
CREATE INDEX ix_meeting_deferrals_user_id ON meeting_deferrals (user_id);

-- memify_logs
CREATE TABLE memify_logs (
	kb_id UUID NOT NULL, 
	trigger VARCHAR(50) NOT NULL, 
	nodes_pruned INTEGER NOT NULL, 
	edges_pruned INTEGER NOT NULL, 
	edges_strengthened INTEGER NOT NULL, 
	edges_weakened INTEGER NOT NULL, 
	facts_derived INTEGER NOT NULL, 
	entities_merged INTEGER NOT NULL, 
	duration_seconds NUMERIC(10, 2) NOT NULL, 
	details JSONB, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id)
);

CREATE INDEX ix_memify_logs_kb_id ON memify_logs (kb_id);

-- messages
CREATE TABLE messages (
	conversation_id UUID NOT NULL, 
	role VARCHAR(20) NOT NULL, 
	content TEXT NOT NULL, 
	blocks JSONB, 
	tool_calls JSONB, 
	input_tokens INTEGER NOT NULL, 
	output_tokens INTEGER NOT NULL, 
	cost NUMERIC(10, 6) NOT NULL, 
	model_used VARCHAR(100), 
	duration_ms INTEGER, 
	attachments JSONB, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(conversation_id) REFERENCES conversations (id) ON DELETE CASCADE
);

CREATE INDEX ix_messages_conversation_created ON messages (conversation_id, created_at);
CREATE INDEX ix_messages_conversation_id ON messages (conversation_id);

-- payouts
CREATE TABLE payouts (
	creator_id UUID NOT NULL, 
	subscription_id UUID, 
	agent_id UUID NOT NULL, 
	stripe_transfer_id VARCHAR(255), 
	stripe_charge_id VARCHAR(255), 
	amount_total NUMERIC(10, 2) NOT NULL, 
	platform_fee NUMERIC(10, 2) NOT NULL, 
	creator_amount NUMERIC(10, 2) NOT NULL, 
	currency VARCHAR(3) NOT NULL, 
	status VARCHAR(50) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(creator_id) REFERENCES users (id), 
	FOREIGN KEY(subscription_id) REFERENCES subscriptions (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id)
);

CREATE INDEX ix_payouts_agent_id ON payouts (agent_id);
CREATE INDEX ix_payouts_subscription ON payouts (subscription_id);
CREATE INDEX ix_payouts_creator ON payouts (creator_id, created_at);
CREATE INDEX ix_payouts_creator_id ON payouts (creator_id);

-- persona_items
CREATE TABLE persona_items (
	user_id UUID NOT NULL, 
	kb_id UUID, 
	persona_scope VARCHAR(80) NOT NULL, 
	kind VARCHAR(30) NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	source VARCHAR(500), 
	byte_size INTEGER NOT NULL, 
	chunk_count INTEGER NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	pinecone_ids TEXT[], 
	metadata JSONB, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_persona_items_kb_id ON persona_items (kb_id);
CREATE INDEX ix_persona_items_tenant_id ON persona_items (tenant_id);
CREATE INDEX ix_persona_items_persona_scope ON persona_items (persona_scope);
CREATE INDEX ix_persona_items_user_scope ON persona_items (user_id, persona_scope);
CREATE INDEX ix_persona_items_user_id ON persona_items (user_id);

-- pipeline_run_diffs
CREATE TABLE pipeline_run_diffs (
	pipeline_id UUID NOT NULL, 
	execution_id UUID NOT NULL, 
	node_id VARCHAR(255) NOT NULL, 
	node_kind VARCHAR(64) NOT NULL, 
	node_target VARCHAR(255), 
	error_class VARCHAR(128) NOT NULL, 
	error_message TEXT NOT NULL, 
	error_traceback TEXT, 
	expected_shape JSONB, 
	observed_shape JSONB, 
	expected_sample JSONB, 
	observed_sample JSONB, 
	upstream_inputs JSONB, 
	recent_success_count INTEGER NOT NULL, 
	recent_failure_count INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(pipeline_id) REFERENCES agents (id) ON DELETE CASCADE, 
	FOREIGN KEY(execution_id) REFERENCES executions (id) ON DELETE CASCADE, 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_pipeline_run_diffs_pipeline_id ON pipeline_run_diffs (pipeline_id);
CREATE INDEX ix_pipeline_run_diffs_execution_id ON pipeline_run_diffs (execution_id);
CREATE INDEX ix_pipeline_run_diffs_tenant_id ON pipeline_run_diffs (tenant_id);

-- retrieval_feedback
CREATE TABLE retrieval_feedback (
	kb_id UUID NOT NULL, 
	execution_id UUID, 
	query TEXT NOT NULL, 
	search_mode VARCHAR(50) NOT NULL, 
	result_entity_ids JSONB, 
	result_chunk_ids JSONB, 
	rating INTEGER NOT NULL, 
	comment TEXT, 
	latency_ms INTEGER NOT NULL, 
	result_count INTEGER NOT NULL, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(execution_id) REFERENCES executions (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_retrieval_feedback_kb_id ON retrieval_feedback (kb_id);
CREATE INDEX ix_retrieval_feedback_kb_mode ON retrieval_feedback (kb_id, search_mode);
CREATE INDEX ix_retrieval_feedback_tenant_id ON retrieval_feedback (tenant_id);
CREATE INDEX ix_retrieval_feedback_kb_exec ON retrieval_feedback (kb_id, execution_id);

-- retrieval_metrics
CREATE TABLE retrieval_metrics (
	kb_id UUID NOT NULL, 
	agent_id UUID, 
	period_start TIMESTAMP WITH TIME ZONE NOT NULL, 
	period_end TIMESTAMP WITH TIME ZONE NOT NULL, 
	search_mode VARCHAR(50) NOT NULL, 
	query_count INTEGER NOT NULL, 
	avg_rating NUMERIC(5, 4), 
	avg_latency_ms INTEGER NOT NULL, 
	p95_latency_ms INTEGER NOT NULL, 
	positive_feedback INTEGER NOT NULL, 
	negative_feedback INTEGER NOT NULL, 
	graph_hops_used INTEGER NOT NULL, 
	entities_in_results INTEGER NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(agent_id) REFERENCES agents (id)
);

CREATE INDEX ix_retrieval_metrics_kb_id ON retrieval_metrics (kb_id);
CREATE INDEX ix_retrieval_metrics_kb_mode_period ON retrieval_metrics (kb_id, search_mode, period_start);

-- user_collection_grants
CREATE TABLE user_collection_grants (
	user_id UUID NOT NULL, 
	collection_id UUID NOT NULL, 
	permission collection_permission NOT NULL, 
	granted_by UUID, 
	granted_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	id UUID NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_user_collection_grant UNIQUE (user_id, collection_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(collection_id) REFERENCES knowledge_collections (id) ON DELETE CASCADE, 
	FOREIGN KEY(granted_by) REFERENCES users (id)
);

CREATE INDEX ix_user_collection_grants_user ON user_collection_grants (user_id);
CREATE INDEX ix_user_collection_grants_collection ON user_collection_grants (collection_id);

-- cognify_reports
CREATE TABLE cognify_reports (
	job_id UUID NOT NULL, 
	kb_id UUID NOT NULL, 
	entities_by_type JSONB NOT NULL, 
	top_entities JSONB NOT NULL, 
	relationship_types JSONB NOT NULL, 
	new_entities INTEGER NOT NULL, 
	merged_entities INTEGER NOT NULL, 
	new_relationships INTEGER NOT NULL, 
	strengthened_relationships INTEGER NOT NULL, 
	documents_processed INTEGER NOT NULL, 
	chunks_analyzed INTEGER NOT NULL, 
	processing_details JSONB, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (job_id), 
	FOREIGN KEY(job_id) REFERENCES cognify_jobs (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id)
);

CREATE INDEX ix_cognify_reports_kb_id ON cognify_reports (kb_id);

-- graph_relationships
CREATE TABLE graph_relationships (
	kb_id UUID NOT NULL, 
	source_entity_id UUID NOT NULL, 
	target_entity_id UUID NOT NULL, 
	relationship_type VARCHAR(200) NOT NULL, 
	description TEXT, 
	properties JSONB, 
	source_doc_ids JSONB, 
	neo4j_rel_id VARCHAR(100), 
	weight NUMERIC(5, 4) NOT NULL, 
	access_count INTEGER NOT NULL, 
	confidence NUMERIC(5, 4) NOT NULL, 
	id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(kb_id) REFERENCES knowledge_collections (id), 
	FOREIGN KEY(source_entity_id) REFERENCES graph_entities (id), 
	FOREIGN KEY(target_entity_id) REFERENCES graph_entities (id)
);

CREATE INDEX ix_graph_rels_source_target ON graph_relationships (source_entity_id, target_entity_id);
CREATE INDEX ix_graph_rels_kb_type ON graph_relationships (kb_id, relationship_type);
CREATE INDEX ix_graph_relationships_kb_id ON graph_relationships (kb_id);

-- pipeline_patch_proposals
CREATE TABLE pipeline_patch_proposals (
	pipeline_id UUID NOT NULL, 
	triggering_diff_id UUID, 
	triggering_execution_id UUID, 
	author_agent_id UUID, 
	title VARCHAR(255) NOT NULL, 
	rationale TEXT NOT NULL, 
	confidence NUMERIC(3, 2) NOT NULL, 
	risk_level VARCHAR(16) NOT NULL, 
	dsl_before JSONB NOT NULL, 
	json_patch JSONB NOT NULL, 
	dsl_after JSONB NOT NULL, 
	dsl_before_sha256 VARCHAR(64), 
	applied_snapshot JSONB, 
	status pipeline_patch_status NOT NULL, 
	decided_by UUID, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	rolled_back_at TIMESTAMP WITH TIME ZONE, 
	rolled_back_by UUID, 
	id UUID NOT NULL, 
	tenant_id UUID NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(pipeline_id) REFERENCES agents (id) ON DELETE CASCADE, 
	FOREIGN KEY(triggering_diff_id) REFERENCES pipeline_run_diffs (id) ON DELETE SET NULL, 
	FOREIGN KEY(triggering_execution_id) REFERENCES executions (id) ON DELETE SET NULL, 
	FOREIGN KEY(decided_by) REFERENCES users (id), 
	FOREIGN KEY(rolled_back_by) REFERENCES users (id), 
	FOREIGN KEY(tenant_id) REFERENCES tenants (id)
);

CREATE INDEX ix_pipeline_patch_proposals_pipeline_id ON pipeline_patch_proposals (pipeline_id);
CREATE INDEX ix_pipeline_patch_proposals_tenant_id ON pipeline_patch_proposals (tenant_id);

COMMIT;
