"""Generate a static bootstrap_schema.sql from the ORM models.

This is a developer-readable single-file snapshot of the entire schema.
Regenerate after every model/migration change:

    cd packages/db && python -m generate_bootstrap_sql

The actual install path uses ``packages/db/bootstrap.py`` (which calls
``Base.metadata.create_all`` against the live DB and then runs
``alembic stamp heads``). This SQL file is for humans to read.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def main() -> int:
    from sqlalchemy.dialects import postgresql
    from sqlalchemy.schema import CreateIndex, CreateTable

    import models  # noqa: F401  — registers tables on Base.metadata
    from models.base import Base

    out = ROOT / "bootstrap_schema.sql"
    pg = postgresql.dialect()

    lines: list[str] = [
        "-- Generated by packages/db/generate_bootstrap_sql.py",
        "-- Single-file schema snapshot for fresh installs.",
        "--",
        "-- Live deploys do NOT run this file directly. They run",
        "-- packages/db/bootstrap.py which calls Base.metadata.create_all()",
        "-- against the DB engine — the same source of truth, programmatically.",
        "-- Use this file for human inspection, code review, and as a",
        "-- portable schema reference for downstream consumers.",
        "--",
        "-- After install, alembic is stamped at heads so future schema",
        "-- changes go through `alembic upgrade heads` as usual.",
        "",
        "BEGIN;",
        "",
    ]

    for table in Base.metadata.sorted_tables:
        ddl = str(CreateTable(table).compile(dialect=pg)).strip()
        lines.append(f"-- {table.name}")
        lines.append(ddl + ";")
        lines.append("")
        for ix in table.indexes:
            ix_ddl = str(CreateIndex(ix).compile(dialect=pg)).strip()
            lines.append(ix_ddl + ";")
        if table.indexes:
            lines.append("")

    lines.append("COMMIT;")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} ({len(Base.metadata.sorted_tables)} tables)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
